// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/replay/v1/replay.proto

package replayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplayRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	SourceRequestId string                 `protobuf:"bytes,2,opt,name=source_request_id,json=sourceRequestId,proto3" json:"source_request_id,omitempty"`
	HttpMethod      string                 `protobuf:"bytes,3,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	TargetUrl       string                 `protobuf:"bytes,4,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	Headers         map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body            []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplayRequest) Reset() {
	*x = ReplayRequest{}
	mi := &file_proto_replay_v1_replay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRequest) ProtoMessage() {}

func (x *ReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replay_v1_replay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRequest.ProtoReflect.Descriptor instead.
func (*ReplayRequest) Descriptor() ([]byte, []int) {
	return file_proto_replay_v1_replay_proto_rawDescGZIP(), []int{0}
}

func (x *ReplayRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReplayRequest) GetSourceRequestId() string {
	if x != nil {
		return x.SourceRequestId
	}
	return ""
}

func (x *ReplayRequest) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *ReplayRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *ReplayRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ReplayRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ReplayResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ResponseStatus int32                  `protobuf:"varint,2,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	Headers        map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body           []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	LatencyMs      int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplayResponse) Reset() {
	*x = ReplayResponse{}
	mi := &file_proto_replay_v1_replay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayResponse) ProtoMessage() {}

func (x *ReplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replay_v1_replay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayResponse.ProtoReflect.Descriptor instead.
func (*ReplayResponse) Descriptor() ([]byte, []int) {
	return file_proto_replay_v1_replay_proto_rawDescGZIP(), []int{1}
}

func (x *ReplayResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReplayResponse) GetResponseStatus() int32 {
	if x != nil {
		return x.ResponseStatus
	}
	return 0
}

func (x *ReplayResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ReplayResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ReplayResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ReplayResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_replay_v1_replay_proto protoreflect.FileDescriptor

const file_proto_replay_v1_replay_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/replay/v1/replay.proto\x12\x15apisentinel.replay.v1\"\xaf\x02\n" +
	"\rReplayRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12*\n" +
	"\x11source_request_id\x18\x02 \x01(\tR\x0fsourceRequestId\x12\x1f\n" +
	"\vhttp_method\x18\x03 \x01(\tR\n" +
	"httpMethod\x12\x1d\n" +
	"\n" +
	"target_url\x18\x04 \x01(\tR\ttargetUrl\x12K\n" +
	"\aheaders\x18\x05 \x03(\v21.apisentinel.replay.v1.ReplayRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x02\n" +
	"\x0eReplayResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12'\n" +
	"\x0fresponse_status\x18\x02 \x01(\x05R\x0eresponseStatus\x12L\n" +
	"\aheaders\x18\x03 \x03(\v22.apisentinel.replay.v1.ReplayResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BJZHgithub.com/apisentinel/apisentinel/pkg/genproto/proto/replay/v1;replayv1b\x06proto3"

var (
	file_proto_replay_v1_replay_proto_rawDescOnce sync.Once
	file_proto_replay_v1_replay_proto_rawDescData []byte
)

func file_proto_replay_v1_replay_proto_rawDescGZIP() []byte {
	file_proto_replay_v1_replay_proto_rawDescOnce.Do(func() {
		file_proto_replay_v1_replay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_replay_v1_replay_proto_rawDesc), len(file_proto_replay_v1_replay_proto_rawDesc)))
	})
	return file_proto_replay_v1_replay_proto_rawDescData
}

var file_proto_replay_v1_replay_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_replay_v1_replay_proto_goTypes = []any{
	(*ReplayRequest)(nil),  // 0: apisentinel.replay.v1.ReplayRequest
	(*ReplayResponse)(nil), // 1: apisentinel.replay.v1.ReplayResponse
	nil,                    // 2: apisentinel.replay.v1.ReplayRequest.HeadersEntry
	nil,                    // 3: apisentinel.replay.v1.ReplayResponse.HeadersEntry
}
var file_proto_replay_v1_replay_proto_depIdxs = []int32{
	2, // 0: apisentinel.replay.v1.ReplayRequest.headers:type_name -> apisentinel.replay.v1.ReplayRequest.HeadersEntry
	3, // 1: apisentinel.replay.v1.ReplayResponse.headers:type_name -> apisentinel.replay.v1.ReplayResponse.HeadersEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_replay_v1_replay_proto_init() }
func file_proto_replay_v1_replay_proto_init() {
	if File_proto_replay_v1_replay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_replay_v1_replay_proto_rawDesc), len(file_proto_replay_v1_replay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_replay_v1_replay_proto_goTypes,
		DependencyIndexes: file_proto_replay_v1_replay_proto_depIdxs,
		MessageInfos:      file_proto_replay_v1_replay_proto_msgTypes,
	}.Build()
	File_proto_replay_v1_replay_proto = out.File
	file_proto_replay_v1_replay_proto_goTypes = nil
	file_proto_replay_v1_replay_proto_depIdxs = nil
}
