// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alert.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlertChannel = `-- name: CreateAlertChannel :one
INSERT INTO alert_channels (
    project_id,
    name,
    channel_type,
    webhook_url,
    min_severity,
    is_enabled
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, project_id, name, channel_type, webhook_url, min_severity, is_enabled, created_at
`

type CreateAlertChannelParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Name        string      `json:"name"`
	ChannelType string      `json:"channel_type"`
	WebhookUrl  string      `json:"webhook_url"`
	MinSeverity string      `json:"min_severity"`
	IsEnabled   bool        `json:"is_enabled"`
}

func (q *Queries) CreateAlertChannel(ctx context.Context, arg CreateAlertChannelParams) (AlertChannel, error) {
	row := q.db.QueryRow(ctx, createAlertChannel,
		arg.ProjectID,
		arg.Name,
		arg.ChannelType,
		arg.WebhookUrl,
		arg.MinSeverity,
		arg.IsEnabled,
	)
	var i AlertChannel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ChannelType,
		&i.WebhookUrl,
		&i.MinSeverity,
		&i.IsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlertChannel = `-- name: DeleteAlertChannel :exec
DELETE FROM alert_channels
WHERE id = $1
`

func (q *Queries) DeleteAlertChannel(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlertChannel, id)
	return err
}

const getAlertChannelByID = `-- name: GetAlertChannelByID :one
SELECT id, project_id, name, channel_type, webhook_url, min_severity, is_enabled, created_at FROM alert_channels
WHERE id = $1
`

func (q *Queries) GetAlertChannelByID(ctx context.Context, id pgtype.UUID) (AlertChannel, error) {
	row := q.db.QueryRow(ctx, getAlertChannelByID, id)
	var i AlertChannel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ChannelType,
		&i.WebhookUrl,
		&i.MinSeverity,
		&i.IsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const listAlertChannelsByProject = `-- name: ListAlertChannelsByProject :many
SELECT id, project_id, name, channel_type, webhook_url, min_severity, is_enabled, created_at FROM alert_channels
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAlertChannelsByProject(ctx context.Context, projectID pgtype.UUID) ([]AlertChannel, error) {
	rows, err := q.db.Query(ctx, listAlertChannelsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertChannel
	for rows.Next() {
		var i AlertChannel
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.ChannelType,
			&i.WebhookUrl,
			&i.MinSeverity,
			&i.IsEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleAlertChannel = `-- name: ToggleAlertChannel :one
UPDATE alert_channels
SET is_enabled = $2
WHERE id = $1
RETURNING id, project_id, name, channel_type, webhook_url, min_severity, is_enabled, created_at
`

type ToggleAlertChannelParams struct {
	ID        pgtype.UUID `json:"id"`
	IsEnabled bool        `json:"is_enabled"`
}

func (q *Queries) ToggleAlertChannel(ctx context.Context, arg ToggleAlertChannelParams) (AlertChannel, error) {
	row := q.db.QueryRow(ctx, toggleAlertChannel, arg.ID, arg.IsEnabled)
	var i AlertChannel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ChannelType,
		&i.WebhookUrl,
		&i.MinSeverity,
		&i.IsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const verifyAlertChannelOwnership = `-- name: VerifyAlertChannelOwnership :one
SELECT ac.id
FROM alert_channels ac
JOIN projects p ON p.id = ac.project_id
WHERE ac.id = $1 AND p.organization_id = $2
LIMIT 1
`

type VerifyAlertChannelOwnershipParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) VerifyAlertChannelOwnership(ctx context.Context, arg VerifyAlertChannelOwnershipParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyAlertChannelOwnership, arg.ID, arg.OrganizationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
