// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (project_id, name, key_prefix, key_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, key_prefix, created_by, expires_at, last_used_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	KeyPrefix string             `json:"key_prefix"`
	KeyHash   string             `json:"key_hash"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateAPIKeyRow struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ProjectID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyPrefix,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys
WHERE id = $1 AND project_id = $2
`

type DeleteAPIKeyParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.ProjectID)
	return err
}

const getAPIKeyByPrefixAndHash = `-- name: GetAPIKeyByPrefixAndHash :one
SELECT id, project_id, name, key_prefix, key_hash, created_by, expires_at, last_used_at, revoked_at, created_at
FROM api_keys
WHERE key_prefix = $1
  AND key_hash = $2
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

type GetAPIKeyByPrefixAndHashParams struct {
	KeyPrefix string `json:"key_prefix"`
	KeyHash   string `json:"key_hash"`
}

func (q *Queries) GetAPIKeyByPrefixAndHash(ctx context.Context, arg GetAPIKeyByPrefixAndHashParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefixAndHash, arg.KeyPrefix, arg.KeyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByProject = `-- name: ListAPIKeysByProject :many
SELECT id, project_id, name, key_prefix, created_by, expires_at, last_used_at, revoked_at, created_at
FROM api_keys
WHERE project_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysByProjectRow struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAPIKeysByProject(ctx context.Context, projectID pgtype.UUID) ([]ListAPIKeysByProjectRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysByProjectRow
	for rows.Next() {
		var i ListAPIKeysByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.KeyPrefix,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET revoked_at = NOW()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, key_prefix, revoked_at
`

type RevokeAPIKeyParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

type RevokeAPIKeyRow struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	KeyPrefix string             `json:"key_prefix"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (RevokeAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.ProjectID)
	var i RevokeAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyPrefix,
		&i.RevokedAt,
	)
	return i, err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}
