// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    organization_id,
    project_id,
    user_id,
    action,
    resource_type,
    resource_id,
    justification,
    ip_address,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, organization_id, project_id, user_id, action, resource_type, resource_id, justification, ip_address, metadata, created_at
`

type CreateAuditLogParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Action         string      `json:"action"`
	ResourceType   string      `json:"resource_type"`
	ResourceID     string      `json:"resource_id"`
	Justification  pgtype.Text `json:"justification"`
	IpAddress      pgtype.Text `json:"ip_address"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.OrganizationID,
		arg.ProjectID,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Justification,
		arg.IpAddress,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Justification,
		&i.IpAddress,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsByOrganization = `-- name: ListAuditLogsByOrganization :many
SELECT id, organization_id, project_id, user_id, action, resource_type, resource_id, justification, ip_address, metadata, created_at FROM audit_logs
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByOrganizationParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListAuditLogsByOrganization(ctx context.Context, arg ListAuditLogsByOrganizationParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Justification,
			&i.IpAddress,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByProject = `-- name: ListAuditLogsByProject :many
SELECT id, organization_id, project_id, user_id, action, resource_type, resource_id, justification, ip_address, metadata, created_at FROM audit_logs
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListAuditLogsByProject(ctx context.Context, arg ListAuditLogsByProjectParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Justification,
			&i.IpAddress,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
