// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingDeliveryJobs = `-- name: ClaimPendingDeliveryJobs :many
UPDATE delivery_jobs
SET status = 'PROCESSING',
    locked_at = NOW(),
    locked_by = $1,
    updated_at = NOW()
WHERE id IN (
    SELECT id FROM delivery_jobs
    WHERE status IN ('PENDING', 'RETRY_WAIT')
      AND next_retry_at <= NOW()
      AND (locked_at IS NULL OR locked_at < NOW() - INTERVAL '2 minutes')
    ORDER BY next_retry_at ASC
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, endpoint_id, request_id, target_url, status, attempts, max_retries, next_retry_at, locked_at, locked_by, idempotency_key, last_error, payload_mode, created_at, updated_at, completed_at
`

type ClaimPendingDeliveryJobsParams struct {
	LockedBy pgtype.Text `json:"locked_by"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ClaimPendingDeliveryJobs(ctx context.Context, arg ClaimPendingDeliveryJobsParams) ([]DeliveryJob, error) {
	rows, err := q.db.Query(ctx, claimPendingDeliveryJobs, arg.LockedBy, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryJob
	for rows.Next() {
		var i DeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.RequestID,
			&i.TargetUrl,
			&i.Status,
			&i.Attempts,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.IdempotencyKey,
			&i.LastError,
			&i.PayloadMode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeDeliveryJob = `-- name: CompleteDeliveryJob :one
UPDATE delivery_jobs
SET status = 'DELIVERED',
    attempts = attempts + 1,
    locked_at = NULL,
    locked_by = NULL,
    last_error = NULL,
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, endpoint_id, request_id, target_url, status, attempts, max_retries, next_retry_at, locked_at, locked_by, idempotency_key, last_error, payload_mode, created_at, updated_at, completed_at
`

func (q *Queries) CompleteDeliveryJob(ctx context.Context, id pgtype.UUID) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, completeDeliveryJob, id)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestID,
		&i.TargetUrl,
		&i.Status,
		&i.Attempts,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.IdempotencyKey,
		&i.LastError,
		&i.PayloadMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countDeliveryJobsByProjectAndStatus = `-- name: CountDeliveryJobsByProjectAndStatus :many
SELECT dj.status, COUNT(*) as count
FROM delivery_jobs dj
JOIN endpoints e ON e.id = dj.endpoint_id
WHERE e.project_id = $1
GROUP BY dj.status
`

type CountDeliveryJobsByProjectAndStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountDeliveryJobsByProjectAndStatus(ctx context.Context, projectID pgtype.UUID) ([]CountDeliveryJobsByProjectAndStatusRow, error) {
	rows, err := q.db.Query(ctx, countDeliveryJobsByProjectAndStatus, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDeliveryJobsByProjectAndStatusRow
	for rows.Next() {
		var i CountDeliveryJobsByProjectAndStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDeliveryJob = `-- name: CreateDeliveryJob :one
INSERT INTO delivery_jobs (
    endpoint_id,
    request_id,
    target_url,
    status,
    max_retries,
    idempotency_key,
    payload_mode,
    next_retry_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
)
RETURNING id, endpoint_id, request_id, target_url, status, attempts, max_retries, next_retry_at, locked_at, locked_by, idempotency_key, last_error, payload_mode, created_at, updated_at, completed_at
`

type CreateDeliveryJobParams struct {
	EndpointID     pgtype.UUID `json:"endpoint_id"`
	RequestID      pgtype.UUID `json:"request_id"`
	TargetUrl      string      `json:"target_url"`
	Status         string      `json:"status"`
	MaxRetries     int32       `json:"max_retries"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	PayloadMode    string      `json:"payload_mode"`
}

func (q *Queries) CreateDeliveryJob(ctx context.Context, arg CreateDeliveryJobParams) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, createDeliveryJob,
		arg.EndpointID,
		arg.RequestID,
		arg.TargetUrl,
		arg.Status,
		arg.MaxRetries,
		arg.IdempotencyKey,
		arg.PayloadMode,
	)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestID,
		&i.TargetUrl,
		&i.Status,
		&i.Attempts,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.IdempotencyKey,
		&i.LastError,
		&i.PayloadMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failDeliveryJob = `-- name: FailDeliveryJob :one
UPDATE delivery_jobs
SET status = $2,
    attempts = attempts + 1,
    locked_at = NULL,
    locked_by = NULL,
    last_error = $3,
    next_retry_at = $4,
    updated_at = NOW(),
    completed_at = CASE WHEN $2 = 'DEAD_LETTER' THEN NOW() ELSE completed_at END
WHERE id = $1
RETURNING id, endpoint_id, request_id, target_url, status, attempts, max_retries, next_retry_at, locked_at, locked_by, idempotency_key, last_error, payload_mode, created_at, updated_at, completed_at
`

type FailDeliveryJobParams struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	LastError   pgtype.Text        `json:"last_error"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) FailDeliveryJob(ctx context.Context, arg FailDeliveryJobParams) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, failDeliveryJob,
		arg.ID,
		arg.Status,
		arg.LastError,
		arg.NextRetryAt,
	)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestID,
		&i.TargetUrl,
		&i.Status,
		&i.Attempts,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.IdempotencyKey,
		&i.LastError,
		&i.PayloadMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getDeliveryJobByID = `-- name: GetDeliveryJobByID :one
SELECT id, endpoint_id, request_id, target_url, status, attempts, max_retries, next_retry_at, locked_at, locked_by, idempotency_key, last_error, payload_mode, created_at, updated_at, completed_at FROM delivery_jobs
WHERE id = $1
`

func (q *Queries) GetDeliveryJobByID(ctx context.Context, id pgtype.UUID) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, getDeliveryJobByID, id)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestID,
		&i.TargetUrl,
		&i.Status,
		&i.Attempts,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.IdempotencyKey,
		&i.LastError,
		&i.PayloadMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getDeliveryJobByRequestID = `-- name: GetDeliveryJobByRequestID :one
SELECT id, endpoint_id, request_id, target_url, status, attempts, max_retries, next_retry_at, locked_at, locked_by, idempotency_key, last_error, payload_mode, created_at, updated_at, completed_at FROM delivery_jobs
WHERE request_id = $1
LIMIT 1
`

func (q *Queries) GetDeliveryJobByRequestID(ctx context.Context, requestID pgtype.UUID) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, getDeliveryJobByRequestID, requestID)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestID,
		&i.TargetUrl,
		&i.Status,
		&i.Attempts,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.IdempotencyKey,
		&i.LastError,
		&i.PayloadMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listDeliveryAttemptsByJobID = `-- name: ListDeliveryAttemptsByJobID :many
SELECT id, job_id, attempt_number, started_at, finished_at, latency_ms, response_status_code, error_type, error_message, request_headers_sent, response_headers_received, response_body_snippet, created_at FROM delivery_attempts
WHERE job_id = $1
ORDER BY attempt_number ASC
`

func (q *Queries) ListDeliveryAttemptsByJobID(ctx context.Context, jobID pgtype.UUID) ([]DeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listDeliveryAttemptsByJobID, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryAttempt
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AttemptNumber,
			&i.StartedAt,
			&i.FinishedAt,
			&i.LatencyMs,
			&i.ResponseStatusCode,
			&i.ErrorType,
			&i.ErrorMessage,
			&i.RequestHeadersSent,
			&i.ResponseHeadersReceived,
			&i.ResponseBodySnippet,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryJobsByEndpoint = `-- name: ListDeliveryJobsByEndpoint :many
SELECT id, endpoint_id, request_id, target_url, status, attempts, max_retries, next_retry_at, locked_at, locked_by, idempotency_key, last_error, payload_mode, created_at, updated_at, completed_at FROM delivery_jobs
WHERE endpoint_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDeliveryJobsByEndpointParams struct {
	EndpointID pgtype.UUID `json:"endpoint_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListDeliveryJobsByEndpoint(ctx context.Context, arg ListDeliveryJobsByEndpointParams) ([]DeliveryJob, error) {
	rows, err := q.db.Query(ctx, listDeliveryJobsByEndpoint, arg.EndpointID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryJob
	for rows.Next() {
		var i DeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.RequestID,
			&i.TargetUrl,
			&i.Status,
			&i.Attempts,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.IdempotencyKey,
			&i.LastError,
			&i.PayloadMode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDeliveryAttempt = `-- name: RecordDeliveryAttempt :one
INSERT INTO delivery_attempts (
    job_id,
    attempt_number,
    started_at,
    finished_at,
    latency_ms,
    response_status_code,
    error_type,
    error_message,
    request_headers_sent,
    response_headers_received,
    response_body_snippet
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, job_id, attempt_number, started_at, finished_at, latency_ms, response_status_code, error_type, error_message, request_headers_sent, response_headers_received, response_body_snippet, created_at
`

type RecordDeliveryAttemptParams struct {
	JobID                   pgtype.UUID        `json:"job_id"`
	AttemptNumber           int32              `json:"attempt_number"`
	StartedAt               pgtype.Timestamptz `json:"started_at"`
	FinishedAt              pgtype.Timestamptz `json:"finished_at"`
	LatencyMs               int32              `json:"latency_ms"`
	ResponseStatusCode      pgtype.Int4        `json:"response_status_code"`
	ErrorType               pgtype.Text        `json:"error_type"`
	ErrorMessage            pgtype.Text        `json:"error_message"`
	RequestHeadersSent      []byte             `json:"request_headers_sent"`
	ResponseHeadersReceived []byte             `json:"response_headers_received"`
	ResponseBodySnippet     pgtype.Text        `json:"response_body_snippet"`
}

func (q *Queries) RecordDeliveryAttempt(ctx context.Context, arg RecordDeliveryAttemptParams) (DeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, recordDeliveryAttempt,
		arg.JobID,
		arg.AttemptNumber,
		arg.StartedAt,
		arg.FinishedAt,
		arg.LatencyMs,
		arg.ResponseStatusCode,
		arg.ErrorType,
		arg.ErrorMessage,
		arg.RequestHeadersSent,
		arg.ResponseHeadersReceived,
		arg.ResponseBodySnippet,
	)
	var i DeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptNumber,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LatencyMs,
		&i.ResponseStatusCode,
		&i.ErrorType,
		&i.ErrorMessage,
		&i.RequestHeadersSent,
		&i.ResponseHeadersReceived,
		&i.ResponseBodySnippet,
		&i.CreatedAt,
	)
	return i, err
}

const recoverStaleDeliveryJobs = `-- name: RecoverStaleDeliveryJobs :exec
UPDATE delivery_jobs
SET status = 'RETRY_WAIT',
    locked_at = NULL,
    locked_by = NULL,
    next_retry_at = NOW(),
    updated_at = NOW()
WHERE status = 'PROCESSING'
  AND locked_at < NOW() - INTERVAL '2 minutes'
`

func (q *Queries) RecoverStaleDeliveryJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, recoverStaleDeliveryJobs)
	return err
}

const requeueDeliveryJob = `-- name: RequeueDeliveryJob :one
UPDATE delivery_jobs
SET status = 'PENDING',
    attempts = 0,
    locked_at = NULL,
    locked_by = NULL,
    next_retry_at = NOW(),
    completed_at = NULL,
    updated_at = NOW()
WHERE id = $1
RETURNING id, endpoint_id, request_id, target_url, status, attempts, max_retries, next_retry_at, locked_at, locked_by, idempotency_key, last_error, payload_mode, created_at, updated_at, completed_at
`

func (q *Queries) RequeueDeliveryJob(ctx context.Context, id pgtype.UUID) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, requeueDeliveryJob, id)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestID,
		&i.TargetUrl,
		&i.Status,
		&i.Attempts,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.IdempotencyKey,
		&i.LastError,
		&i.PayloadMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const verifyDeliveryJobOwnership = `-- name: VerifyDeliveryJobOwnership :one
SELECT j.id
FROM delivery_jobs j
JOIN endpoints e ON e.id = j.endpoint_id
JOIN projects p ON p.id = e.project_id
WHERE j.id = $1 AND p.organization_id = $2
LIMIT 1
`

type VerifyDeliveryJobOwnershipParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) VerifyDeliveryJobOwnership(ctx context.Context, arg VerifyDeliveryJobOwnershipParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyDeliveryJobOwnership, arg.ID, arg.OrganizationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
