// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoints.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints (project_id, slug, name, mode, upstream_url, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, slug, name, mode, is_active, upstream_url, created_at
`

type CreateEndpointParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Slug        string      `json:"slug"`
	Name        string      `json:"name"`
	Mode        string      `json:"mode"`
	UpstreamUrl pgtype.Text `json:"upstream_url"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint,
		arg.ProjectID,
		arg.Slug,
		arg.Name,
		arg.Mode,
		arg.UpstreamUrl,
		arg.IsActive,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Mode,
		&i.IsActive,
		&i.UpstreamUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEndpoint = `-- name: DeleteEndpoint :exec
DELETE FROM endpoints
WHERE id = $1 AND project_id = $2
`

type DeleteEndpointParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) DeleteEndpoint(ctx context.Context, arg DeleteEndpointParams) error {
	_, err := q.db.Exec(ctx, deleteEndpoint, arg.ID, arg.ProjectID)
	return err
}

const deleteEndpointSchema = `-- name: DeleteEndpointSchema :exec
DELETE FROM endpoint_schemas
WHERE endpoint_id = $1
`

func (q *Queries) DeleteEndpointSchema(ctx context.Context, endpointID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEndpointSchema, endpointID)
	return err
}

const getEndpointByID = `-- name: GetEndpointByID :one
SELECT id, project_id, slug, name, mode, is_active, upstream_url, created_at
FROM endpoints
WHERE id = $1 AND project_id = $2 LIMIT 1
`

type GetEndpointByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetEndpointByID(ctx context.Context, arg GetEndpointByIDParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByID, arg.ID, arg.ProjectID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Mode,
		&i.IsActive,
		&i.UpstreamUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getEndpointByIDOnly = `-- name: GetEndpointByIDOnly :one
SELECT id, project_id, slug, name, mode, is_active, upstream_url, created_at
FROM endpoints
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEndpointByIDOnly(ctx context.Context, id pgtype.UUID) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByIDOnly, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Mode,
		&i.IsActive,
		&i.UpstreamUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getEndpointBySlug = `-- name: GetEndpointBySlug :one
SELECT id, project_id, slug, name, mode, is_active, upstream_url, created_at
FROM endpoints
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetEndpointBySlug(ctx context.Context, slug string) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointBySlug, slug)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Mode,
		&i.IsActive,
		&i.UpstreamUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getEndpointSchema = `-- name: GetEndpointSchema :one
SELECT id, endpoint_id, json_schema, created_at, updated_at
FROM endpoint_schemas
WHERE endpoint_id = $1 LIMIT 1
`

func (q *Queries) GetEndpointSchema(ctx context.Context, endpointID pgtype.UUID) (EndpointSchema, error) {
	row := q.db.QueryRow(ctx, getEndpointSchema, endpointID)
	var i EndpointSchema
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.JsonSchema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpointWithOwnership = `-- name: GetEndpointWithOwnership :one
SELECT e.id, e.project_id, p.organization_id
FROM endpoints e
JOIN projects p ON e.project_id = p.id
WHERE e.id = $1 AND p.organization_id = $2
LIMIT 1
`

type GetEndpointWithOwnershipParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetEndpointWithOwnershipRow struct {
	ID             pgtype.UUID `json:"id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetEndpointWithOwnership(ctx context.Context, arg GetEndpointWithOwnershipParams) (GetEndpointWithOwnershipRow, error) {
	row := q.db.QueryRow(ctx, getEndpointWithOwnership, arg.ID, arg.OrganizationID)
	var i GetEndpointWithOwnershipRow
	err := row.Scan(&i.ID, &i.ProjectID, &i.OrganizationID)
	return i, err
}

const listEndpointsByProject = `-- name: ListEndpointsByProject :many
SELECT e.id, e.project_id, e.slug, e.name, e.mode, e.is_active, e.upstream_url, e.created_at,
       COUNT(r.id)::bigint as request_count
FROM endpoints e
LEFT JOIN captured_requests r ON e.id = r.endpoint_id
WHERE e.project_id = $1
GROUP BY e.id
ORDER BY e.created_at DESC
`

type ListEndpointsByProjectRow struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	Slug         string             `json:"slug"`
	Name         string             `json:"name"`
	Mode         string             `json:"mode"`
	IsActive     bool               `json:"is_active"`
	UpstreamUrl  pgtype.Text        `json:"upstream_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	RequestCount int64              `json:"request_count"`
}

func (q *Queries) ListEndpointsByProject(ctx context.Context, projectID pgtype.UUID) ([]ListEndpointsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listEndpointsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEndpointsByProjectRow
	for rows.Next() {
		var i ListEndpointsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Name,
			&i.Mode,
			&i.IsActive,
			&i.UpstreamUrl,
			&i.CreatedAt,
			&i.RequestCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE endpoints
SET name = COALESCE($3, name),
    mode = COALESCE($4, mode),
    is_active = COALESCE($5, is_active),
    upstream_url = COALESCE($6, upstream_url)
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, slug, name, mode, is_active, upstream_url, created_at
`

type UpdateEndpointParams struct {
	ID          pgtype.UUID `json:"id"`
	ProjectID   pgtype.UUID `json:"project_id"`
	Name        string      `json:"name"`
	Mode        string      `json:"mode"`
	IsActive    bool        `json:"is_active"`
	UpstreamUrl pgtype.Text `json:"upstream_url"`
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpoint,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Mode,
		arg.IsActive,
		arg.UpstreamUrl,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Mode,
		&i.IsActive,
		&i.UpstreamUrl,
		&i.CreatedAt,
	)
	return i, err
}

const upsertEndpointSchema = `-- name: UpsertEndpointSchema :one
INSERT INTO endpoint_schemas (endpoint_id, json_schema)
VALUES ($1, $2)
ON CONFLICT (endpoint_id) DO UPDATE SET
    json_schema = EXCLUDED.json_schema,
    updated_at = NOW()
RETURNING id, endpoint_id, json_schema, created_at, updated_at
`

type UpsertEndpointSchemaParams struct {
	EndpointID pgtype.UUID `json:"endpoint_id"`
	JsonSchema []byte      `json:"json_schema"`
}

func (q *Queries) UpsertEndpointSchema(ctx context.Context, arg UpsertEndpointSchemaParams) (EndpointSchema, error) {
	row := q.db.QueryRow(ctx, upsertEndpointSchema, arg.EndpointID, arg.JsonSchema)
	var i EndpointSchema
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.JsonSchema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
