// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSecurityFinding = `-- name: CreateSecurityFinding :one
INSERT INTO security_findings (
    request_id, rule_id, category, type, severity,
    action, field_path, message, evidence_masked, confidence
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, request_id, rule_id, category, type, severity, action, field_path, message, evidence_masked, confidence, created_at
`

type CreateSecurityFindingParams struct {
	RequestID      pgtype.UUID   `json:"request_id"`
	RuleID         pgtype.UUID   `json:"rule_id"`
	Category       string        `json:"category"`
	Type           string        `json:"type"`
	Severity       string        `json:"severity"`
	Action         string        `json:"action"`
	FieldPath      pgtype.Text   `json:"field_path"`
	Message        string        `json:"message"`
	EvidenceMasked pgtype.Text   `json:"evidence_masked"`
	Confidence     pgtype.Float8 `json:"confidence"`
}

func (q *Queries) CreateSecurityFinding(ctx context.Context, arg CreateSecurityFindingParams) (SecurityFinding, error) {
	row := q.db.QueryRow(ctx, createSecurityFinding,
		arg.RequestID,
		arg.RuleID,
		arg.Category,
		arg.Type,
		arg.Severity,
		arg.Action,
		arg.FieldPath,
		arg.Message,
		arg.EvidenceMasked,
		arg.Confidence,
	)
	var i SecurityFinding
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.RuleID,
		&i.Category,
		&i.Type,
		&i.Severity,
		&i.Action,
		&i.FieldPath,
		&i.Message,
		&i.EvidenceMasked,
		&i.Confidence,
		&i.CreatedAt,
	)
	return i, err
}

const getFindingStats = `-- name: GetFindingStats :one
SELECT
    COUNT(*) FILTER (WHERE sf.severity = 'CRITICAL')::bigint as critical_count,
    COUNT(*) FILTER (WHERE sf.severity = 'HIGH')::bigint as high_count,
    COUNT(*) FILTER (WHERE sf.severity = 'MEDIUM')::bigint as medium_count,
    COUNT(*) FILTER (WHERE sf.severity = 'INFO')::bigint as info_count,
    COUNT(*)::bigint as total_count
FROM security_findings sf
JOIN captured_requests cr ON sf.request_id = cr.id
JOIN endpoints e ON cr.endpoint_id = e.id
WHERE e.project_id = $1
`

type GetFindingStatsRow struct {
	CriticalCount int64 `json:"critical_count"`
	HighCount     int64 `json:"high_count"`
	MediumCount   int64 `json:"medium_count"`
	InfoCount     int64 `json:"info_count"`
	TotalCount    int64 `json:"total_count"`
}

func (q *Queries) GetFindingStats(ctx context.Context, projectID pgtype.UUID) (GetFindingStatsRow, error) {
	row := q.db.QueryRow(ctx, getFindingStats, projectID)
	var i GetFindingStatsRow
	err := row.Scan(
		&i.CriticalCount,
		&i.HighCount,
		&i.MediumCount,
		&i.InfoCount,
		&i.TotalCount,
	)
	return i, err
}

const listFindingsByProject = `-- name: ListFindingsByProject :many
SELECT sf.id, sf.request_id, sf.rule_id, sf.category, sf.type, sf.severity,
       sf.action, sf.field_path, sf.message, sf.evidence_masked, sf.confidence, sf.created_at,
       cr.request_id as req_display_id, e.name as endpoint_name
FROM security_findings sf
JOIN captured_requests cr ON sf.request_id = cr.id
JOIN endpoints e ON cr.endpoint_id = e.id
WHERE e.project_id = $1
ORDER BY sf.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFindingsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListFindingsByProjectRow struct {
	ID             pgtype.UUID        `json:"id"`
	RequestID      pgtype.UUID        `json:"request_id"`
	RuleID         pgtype.UUID        `json:"rule_id"`
	Category       string             `json:"category"`
	Type           string             `json:"type"`
	Severity       string             `json:"severity"`
	Action         string             `json:"action"`
	FieldPath      pgtype.Text        `json:"field_path"`
	Message        string             `json:"message"`
	EvidenceMasked pgtype.Text        `json:"evidence_masked"`
	Confidence     pgtype.Float8      `json:"confidence"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ReqDisplayID   string             `json:"req_display_id"`
	EndpointName   string             `json:"endpoint_name"`
}

func (q *Queries) ListFindingsByProject(ctx context.Context, arg ListFindingsByProjectParams) ([]ListFindingsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listFindingsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFindingsByProjectRow
	for rows.Next() {
		var i ListFindingsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.RuleID,
			&i.Category,
			&i.Type,
			&i.Severity,
			&i.Action,
			&i.FieldPath,
			&i.Message,
			&i.EvidenceMasked,
			&i.Confidence,
			&i.CreatedAt,
			&i.ReqDisplayID,
			&i.EndpointName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
