// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forwarding.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDLQRecord = `-- name: CreateDLQRecord :one
INSERT INTO forwarding_dlq (
    endpoint_id,
    request_id,
    target_url,
    attempts,
    last_error,
    payload,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, endpoint_id, request_id, target_url, attempts, last_error, payload, status, created_at, last_attempt_at
`

type CreateDLQRecordParams struct {
	EndpointID pgtype.UUID `json:"endpoint_id"`
	RequestID  pgtype.UUID `json:"request_id"`
	TargetUrl  string      `json:"target_url"`
	Attempts   int32       `json:"attempts"`
	LastError  pgtype.Text `json:"last_error"`
	Payload    pgtype.Text `json:"payload"`
	Status     string      `json:"status"`
}

func (q *Queries) CreateDLQRecord(ctx context.Context, arg CreateDLQRecordParams) (ForwardingDlq, error) {
	row := q.db.QueryRow(ctx, createDLQRecord,
		arg.EndpointID,
		arg.RequestID,
		arg.TargetUrl,
		arg.Attempts,
		arg.LastError,
		arg.Payload,
		arg.Status,
	)
	var i ForwardingDlq
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestID,
		&i.TargetUrl,
		&i.Attempts,
		&i.LastError,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.LastAttemptAt,
	)
	return i, err
}

const getDLQRecordByID = `-- name: GetDLQRecordByID :one
SELECT id, endpoint_id, request_id, target_url, attempts, last_error, payload, status, created_at, last_attempt_at FROM forwarding_dlq
WHERE id = $1
`

func (q *Queries) GetDLQRecordByID(ctx context.Context, id pgtype.UUID) (ForwardingDlq, error) {
	row := q.db.QueryRow(ctx, getDLQRecordByID, id)
	var i ForwardingDlq
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestID,
		&i.TargetUrl,
		&i.Attempts,
		&i.LastError,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.LastAttemptAt,
	)
	return i, err
}

const getForwardingConfigByEndpoint = `-- name: GetForwardingConfigByEndpoint :one
SELECT id, endpoint_id, target_url, max_retries, timeout_ms, custom_headers, is_enabled, created_at FROM forwarding_configs
WHERE endpoint_id = $1
`

func (q *Queries) GetForwardingConfigByEndpoint(ctx context.Context, endpointID pgtype.UUID) (ForwardingConfig, error) {
	row := q.db.QueryRow(ctx, getForwardingConfigByEndpoint, endpointID)
	var i ForwardingConfig
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.TargetUrl,
		&i.MaxRetries,
		&i.TimeoutMs,
		&i.CustomHeaders,
		&i.IsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const listDLQRecordsByEndpoint = `-- name: ListDLQRecordsByEndpoint :many
SELECT id, endpoint_id, request_id, target_url, attempts, last_error, payload, status, created_at, last_attempt_at FROM forwarding_dlq
WHERE endpoint_id = $1
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListDLQRecordsByEndpoint(ctx context.Context, endpointID pgtype.UUID) ([]ForwardingDlq, error) {
	rows, err := q.db.Query(ctx, listDLQRecordsByEndpoint, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForwardingDlq
	for rows.Next() {
		var i ForwardingDlq
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.RequestID,
			&i.TargetUrl,
			&i.Attempts,
			&i.LastError,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.LastAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDLQStatus = `-- name: UpdateDLQStatus :one
UPDATE forwarding_dlq
SET status = $2,
    attempts = attempts + 1,
    last_attempt_at = NOW()
WHERE id = $1
RETURNING id, endpoint_id, request_id, target_url, attempts, last_error, payload, status, created_at, last_attempt_at
`

type UpdateDLQStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateDLQStatus(ctx context.Context, arg UpdateDLQStatusParams) (ForwardingDlq, error) {
	row := q.db.QueryRow(ctx, updateDLQStatus, arg.ID, arg.Status)
	var i ForwardingDlq
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestID,
		&i.TargetUrl,
		&i.Attempts,
		&i.LastError,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.LastAttemptAt,
	)
	return i, err
}

const upsertForwardingConfig = `-- name: UpsertForwardingConfig :one
INSERT INTO forwarding_configs (
    endpoint_id,
    target_url,
    max_retries,
    timeout_ms,
    custom_headers,
    is_enabled
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (endpoint_id) DO UPDATE SET
    target_url = EXCLUDED.target_url,
    max_retries = EXCLUDED.max_retries,
    timeout_ms = EXCLUDED.timeout_ms,
    custom_headers = EXCLUDED.custom_headers,
    is_enabled = EXCLUDED.is_enabled
RETURNING id, endpoint_id, target_url, max_retries, timeout_ms, custom_headers, is_enabled, created_at
`

type UpsertForwardingConfigParams struct {
	EndpointID    pgtype.UUID `json:"endpoint_id"`
	TargetUrl     string      `json:"target_url"`
	MaxRetries    int32       `json:"max_retries"`
	TimeoutMs     int32       `json:"timeout_ms"`
	CustomHeaders []byte      `json:"custom_headers"`
	IsEnabled     bool        `json:"is_enabled"`
}

func (q *Queries) UpsertForwardingConfig(ctx context.Context, arg UpsertForwardingConfigParams) (ForwardingConfig, error) {
	row := q.db.QueryRow(ctx, upsertForwardingConfig,
		arg.EndpointID,
		arg.TargetUrl,
		arg.MaxRetries,
		arg.TimeoutMs,
		arg.CustomHeaders,
		arg.IsEnabled,
	)
	var i ForwardingConfig
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.TargetUrl,
		&i.MaxRetries,
		&i.TimeoutMs,
		&i.CustomHeaders,
		&i.IsEnabled,
		&i.CreatedAt,
	)
	return i, err
}
