// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mock.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMockRule = `-- name: CreateMockRule :one
INSERT INTO mock_rules (endpoint_id, name, condition, status_code, delay_ms, response_headers, response_body, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, endpoint_id, name, condition, status_code, delay_ms, response_headers, response_body, enabled
`

type CreateMockRuleParams struct {
	EndpointID      pgtype.UUID `json:"endpoint_id"`
	Name            string      `json:"name"`
	Condition       []byte      `json:"condition"`
	StatusCode      int32       `json:"status_code"`
	DelayMs         int32       `json:"delay_ms"`
	ResponseHeaders []byte      `json:"response_headers"`
	ResponseBody    []byte      `json:"response_body"`
	Enabled         bool        `json:"enabled"`
}

func (q *Queries) CreateMockRule(ctx context.Context, arg CreateMockRuleParams) (MockRule, error) {
	row := q.db.QueryRow(ctx, createMockRule,
		arg.EndpointID,
		arg.Name,
		arg.Condition,
		arg.StatusCode,
		arg.DelayMs,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.Enabled,
	)
	var i MockRule
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.Name,
		&i.Condition,
		&i.StatusCode,
		&i.DelayMs,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.Enabled,
	)
	return i, err
}

const deleteMockRule = `-- name: DeleteMockRule :exec
DELETE FROM mock_rules
WHERE id = $1 AND endpoint_id = $2
`

type DeleteMockRuleParams struct {
	ID         pgtype.UUID `json:"id"`
	EndpointID pgtype.UUID `json:"endpoint_id"`
}

func (q *Queries) DeleteMockRule(ctx context.Context, arg DeleteMockRuleParams) error {
	_, err := q.db.Exec(ctx, deleteMockRule, arg.ID, arg.EndpointID)
	return err
}

const listMockRulesByEndpoint = `-- name: ListMockRulesByEndpoint :many
SELECT id, endpoint_id, name, condition, status_code, delay_ms, response_headers, response_body, enabled
FROM mock_rules
WHERE endpoint_id = $1
ORDER BY id ASC
`

func (q *Queries) ListMockRulesByEndpoint(ctx context.Context, endpointID pgtype.UUID) ([]MockRule, error) {
	rows, err := q.db.Query(ctx, listMockRulesByEndpoint, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MockRule
	for rows.Next() {
		var i MockRule
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.Name,
			&i.Condition,
			&i.StatusCode,
			&i.DelayMs,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
