// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"token_hash"`
	Status     string             `json:"status"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AlertChannel struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Name        string             `json:"name"`
	ChannelType string             `json:"channel_type"`
	WebhookUrl  string             `json:"webhook_url"`
	MinSeverity string             `json:"min_severity"`
	IsEnabled   bool               `json:"is_enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyHash    string             `json:"key_hash"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CapturedRequest struct {
	ID               pgtype.UUID        `json:"id"`
	EndpointID       pgtype.UUID        `json:"endpoint_id"`
	RequestID        string             `json:"request_id"`
	HttpMethod       string             `json:"http_method"`
	Headers          []byte             `json:"headers"`
	QueryParams      []byte             `json:"query_params"`
	RawBody          pgtype.Text        `json:"raw_body"`
	MaskedBody       pgtype.Text        `json:"masked_body"`
	ParsedJson       []byte             `json:"parsed_json"`
	ClientIp         *netip.Addr        `json:"client_ip"`
	ResponseStatus   pgtype.Int4        `json:"response_status"`
	ProcessingStatus string             `json:"processing_status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Endpoint struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Mode        string             `json:"mode"`
	IsActive    bool               `json:"is_active"`
	UpstreamUrl pgtype.Text        `json:"upstream_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type EndpointSchema struct {
	ID         pgtype.UUID        `json:"id"`
	EndpointID pgtype.UUID        `json:"endpoint_id"`
	JsonSchema []byte             `json:"json_schema"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ForwardingConfig struct {
	ID            pgtype.UUID        `json:"id"`
	EndpointID    pgtype.UUID        `json:"endpoint_id"`
	TargetUrl     string             `json:"target_url"`
	MaxRetries    int32              `json:"max_retries"`
	TimeoutMs     int32              `json:"timeout_ms"`
	CustomHeaders []byte             `json:"custom_headers"`
	IsEnabled     bool               `json:"is_enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ForwardingDlq struct {
	ID            pgtype.UUID        `json:"id"`
	EndpointID    pgtype.UUID        `json:"endpoint_id"`
	RequestID     pgtype.UUID        `json:"request_id"`
	TargetUrl     string             `json:"target_url"`
	Attempts      int32              `json:"attempts"`
	LastError     pgtype.Text        `json:"last_error"`
	Payload       pgtype.Text        `json:"payload"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastAttemptAt pgtype.Timestamptz `json:"last_attempt_at"`
}

type Membership struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MockRule struct {
	ID              pgtype.UUID `json:"id"`
	EndpointID      pgtype.UUID `json:"endpoint_id"`
	Name            string      `json:"name"`
	Condition       []byte      `json:"condition"`
	StatusCode      int32       `json:"status_code"`
	DelayMs         int32       `json:"delay_ms"`
	ResponseHeaders []byte      `json:"response_headers"`
	ResponseBody    []byte      `json:"response_body"`
	Enabled         bool        `json:"enabled"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Policy struct {
	ID            pgtype.UUID        `json:"id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	Name          string             `json:"name"`
	Configuration []byte             `json:"configuration"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Name           string             `json:"name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ReplayJob struct {
	ID              pgtype.UUID        `json:"id"`
	SourceRequestID pgtype.UUID        `json:"source_request_id"`
	TargetType      string             `json:"target_type"`
	TargetUrl       pgtype.Text        `json:"target_url"`
	Status          string             `json:"status"`
	ResponseStatus  pgtype.Int4        `json:"response_status"`
	ResponseBody    pgtype.Text        `json:"response_body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type Rule struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Category      string      `json:"category"`
	RuleType      string      `json:"rule_type"`
	Severity      string      `json:"severity"`
	Enabled       bool        `json:"enabled"`
	Configuration []byte      `json:"configuration"`
}

type SecurityFinding struct {
	ID             pgtype.UUID        `json:"id"`
	RequestID      pgtype.UUID        `json:"request_id"`
	RuleID         pgtype.UUID        `json:"rule_id"`
	Category       string             `json:"category"`
	Type           string             `json:"type"`
	Severity       string             `json:"severity"`
	Action         string             `json:"action"`
	FieldPath      pgtype.Text        `json:"field_path"`
	Message        string             `json:"message"`
	EvidenceMasked pgtype.Text        `json:"evidence_masked"`
	Confidence     pgtype.Float8      `json:"confidence"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
