// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"token_hash"`
	Status     string             `json:"status"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AgentScan struct {
	ID            pgtype.UUID        `json:"id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	AgentID       string             `json:"agent_id"`
	Repository    string             `json:"repository"`
	Branch        string             `json:"branch"`
	CommitHash    string             `json:"commit_hash"`
	ScanType      string             `json:"scan_type"`
	TotalFindings int32              `json:"total_findings"`
	Action        string             `json:"action"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AlertChannel struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Name        string             `json:"name"`
	ChannelType string             `json:"channel_type"`
	WebhookUrl  string             `json:"webhook_url"`
	MinSeverity string             `json:"min_severity"`
	IsEnabled   bool               `json:"is_enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyHash    string             `json:"key_hash"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Action         string             `json:"action"`
	ResourceType   string             `json:"resource_type"`
	ResourceID     string             `json:"resource_id"`
	Justification  pgtype.Text        `json:"justification"`
	IpAddress      pgtype.Text        `json:"ip_address"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type CapturedRequest struct {
	ID               pgtype.UUID        `json:"id"`
	EndpointID       pgtype.UUID        `json:"endpoint_id"`
	RequestID        string             `json:"request_id"`
	HttpMethod       string             `json:"http_method"`
	Headers          []byte             `json:"headers"`
	QueryParams      []byte             `json:"query_params"`
	RawBody          pgtype.Text        `json:"raw_body"`
	MaskedBody       pgtype.Text        `json:"masked_body"`
	ParsedJson       []byte             `json:"parsed_json"`
	ClientIp         *netip.Addr        `json:"client_ip"`
	ResponseStatus   pgtype.Int4        `json:"response_status"`
	ProcessingStatus string             `json:"processing_status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type DeliveryAttempt struct {
	ID                      pgtype.UUID        `json:"id"`
	JobID                   pgtype.UUID        `json:"job_id"`
	AttemptNumber           int32              `json:"attempt_number"`
	StartedAt               pgtype.Timestamptz `json:"started_at"`
	FinishedAt              pgtype.Timestamptz `json:"finished_at"`
	LatencyMs               int32              `json:"latency_ms"`
	ResponseStatusCode      pgtype.Int4        `json:"response_status_code"`
	ErrorType               pgtype.Text        `json:"error_type"`
	ErrorMessage            pgtype.Text        `json:"error_message"`
	RequestHeadersSent      []byte             `json:"request_headers_sent"`
	ResponseHeadersReceived []byte             `json:"response_headers_received"`
	ResponseBodySnippet     pgtype.Text        `json:"response_body_snippet"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type DeliveryJob struct {
	ID             pgtype.UUID        `json:"id"`
	EndpointID     pgtype.UUID        `json:"endpoint_id"`
	RequestID      pgtype.UUID        `json:"request_id"`
	TargetUrl      string             `json:"target_url"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	MaxRetries     int32              `json:"max_retries"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
	LockedAt       pgtype.Timestamptz `json:"locked_at"`
	LockedBy       pgtype.Text        `json:"locked_by"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	LastError      pgtype.Text        `json:"last_error"`
	PayloadMode    string             `json:"payload_mode"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type Endpoint struct {
	ID                  pgtype.UUID        `json:"id"`
	ProjectID           pgtype.UUID        `json:"project_id"`
	Slug                string             `json:"slug"`
	Name                string             `json:"name"`
	Mode                string             `json:"mode"`
	IsActive            bool               `json:"is_active"`
	UpstreamUrl         pgtype.Text        `json:"upstream_url"`
	MaxPayloadSizeBytes int32              `json:"max_payload_size_bytes"`
	RateLimitRpm        int32              `json:"rate_limit_rpm"`
	BurstThreshold      int32              `json:"burst_threshold"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type EndpointSchema struct {
	ID         pgtype.UUID        `json:"id"`
	EndpointID pgtype.UUID        `json:"endpoint_id"`
	JsonSchema []byte             `json:"json_schema"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type EndpointWebhookSecurity struct {
	EndpointID       pgtype.UUID        `json:"endpoint_id"`
	Provider         string             `json:"provider"`
	EncryptedSecret  string             `json:"encrypted_secret"`
	RequireSignature bool               `json:"require_signature"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ForwardingConfig struct {
	ID            pgtype.UUID        `json:"id"`
	EndpointID    pgtype.UUID        `json:"endpoint_id"`
	TargetUrl     string             `json:"target_url"`
	MaxRetries    int32              `json:"max_retries"`
	TimeoutMs     int32              `json:"timeout_ms"`
	CustomHeaders []byte             `json:"custom_headers"`
	IsEnabled     bool               `json:"is_enabled"`
	PayloadMode   string             `json:"payload_mode"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ForwardingDlq struct {
	ID            pgtype.UUID        `json:"id"`
	EndpointID    pgtype.UUID        `json:"endpoint_id"`
	RequestID     pgtype.UUID        `json:"request_id"`
	TargetUrl     string             `json:"target_url"`
	Attempts      int32              `json:"attempts"`
	MaxRetries    int32              `json:"max_retries"`
	LastError     pgtype.Text        `json:"last_error"`
	Payload       pgtype.Text        `json:"payload"`
	PayloadMode   string             `json:"payload_mode"`
	Status        string             `json:"status"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      pgtype.Text        `json:"locked_by"`
	NextRetryAt   pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastAttemptAt pgtype.Timestamptz `json:"last_attempt_at"`
}

type Membership struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MockRule struct {
	ID              pgtype.UUID `json:"id"`
	EndpointID      pgtype.UUID `json:"endpoint_id"`
	Name            string      `json:"name"`
	Condition       []byte      `json:"condition"`
	StatusCode      int32       `json:"status_code"`
	DelayMs         int32       `json:"delay_ms"`
	ResponseHeaders []byte      `json:"response_headers"`
	ResponseBody    []byte      `json:"response_body"`
	Enabled         bool        `json:"enabled"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Policy struct {
	ID            pgtype.UUID        `json:"id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	Name          string             `json:"name"`
	Configuration []byte             `json:"configuration"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Name           string             `json:"name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ReplayJob struct {
	ID              pgtype.UUID        `json:"id"`
	SourceRequestID pgtype.UUID        `json:"source_request_id"`
	TargetType      string             `json:"target_type"`
	TargetUrl       pgtype.Text        `json:"target_url"`
	Environment     string             `json:"environment"`
	LatencyMs       int32              `json:"latency_ms"`
	CustomHeaders   []byte             `json:"custom_headers"`
	Status          string             `json:"status"`
	ResponseStatus  pgtype.Int4        `json:"response_status"`
	ResponseBody    pgtype.Text        `json:"response_body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type ReplayTestRun struct {
	ID             pgtype.UUID        `json:"id"`
	SuiteID        pgtype.UUID        `json:"suite_id"`
	Status         string             `json:"status"`
	TotalSteps     int32              `json:"total_steps"`
	PassedSteps    int32              `json:"passed_steps"`
	FailedSteps    int32              `json:"failed_steps"`
	TotalLatencyMs int32              `json:"total_latency_ms"`
	StepResults    []byte             `json:"step_results"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type ReplayTestSuite struct {
	ID                pgtype.UUID        `json:"id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	RequestIds        []byte             `json:"request_ids"`
	TargetEnvironment string             `json:"target_environment"`
	TargetUrl         pgtype.Text        `json:"target_url"`
	RenewIdempotency  bool               `json:"renew_idempotency"`
	CustomHeaders     []byte             `json:"custom_headers"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Rule struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Category      string      `json:"category"`
	RuleType      string      `json:"rule_type"`
	Severity      string      `json:"severity"`
	Enabled       bool        `json:"enabled"`
	Configuration []byte      `json:"configuration"`
}

type SchemaBaseline struct {
	ID         pgtype.UUID        `json:"id"`
	EndpointID pgtype.UUID        `json:"endpoint_id"`
	Version    int32              `json:"version"`
	SchemaJson []byte             `json:"schema_json"`
	Source     string             `json:"source"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type SchemaDriftEvent struct {
	ID               pgtype.UUID        `json:"id"`
	EndpointID       pgtype.UUID        `json:"endpoint_id"`
	SchemaBaselineID pgtype.UUID        `json:"schema_baseline_id"`
	RequestID        pgtype.UUID        `json:"request_id"`
	DriftType        string             `json:"drift_type"`
	DiffJson         []byte             `json:"diff_json"`
	IsAcknowledged   bool               `json:"is_acknowledged"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type SecurityFinding struct {
	ID             pgtype.UUID        `json:"id"`
	RequestID      pgtype.UUID        `json:"request_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	ScanID         pgtype.UUID        `json:"scan_id"`
	SourceType     string             `json:"source_type"`
	RuleID         pgtype.UUID        `json:"rule_id"`
	Category       string             `json:"category"`
	Type           string             `json:"type"`
	Severity       string             `json:"severity"`
	Action         string             `json:"action"`
	FieldPath      pgtype.Text        `json:"field_path"`
	FilePath       pgtype.Text        `json:"file_path"`
	LineNumber     pgtype.Int4        `json:"line_number"`
	CommitHash     pgtype.Text        `json:"commit_hash"`
	Repository     pgtype.Text        `json:"repository"`
	Message        string             `json:"message"`
	EvidenceMasked pgtype.Text        `json:"evidence_masked"`
	Confidence     pgtype.Float8      `json:"confidence"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
