// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcknowledgeSchemaDrift(ctx context.Context, arg AcknowledgeSchemaDriftParams) (SchemaDriftEvent, error)
	ActivateSchemaBaseline(ctx context.Context, arg ActivateSchemaBaselineParams) (SchemaBaseline, error)
	ClaimPendingDeliveryJobs(ctx context.Context, arg ClaimPendingDeliveryJobsParams) ([]DeliveryJob, error)
	ClaimPendingOutboxJobs(ctx context.Context, arg ClaimPendingOutboxJobsParams) ([]ForwardingDlq, error)
	CompleteDeliveryJob(ctx context.Context, id pgtype.UUID) (DeliveryJob, error)
	CompleteOutboxJob(ctx context.Context, id pgtype.UUID) (ForwardingDlq, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	CreateAgentScan(ctx context.Context, arg CreateAgentScanParams) (AgentScan, error)
	CreateAlertChannel(ctx context.Context, arg CreateAlertChannelParams) (AlertChannel, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateCapturedRequest(ctx context.Context, arg CreateCapturedRequestParams) (CapturedRequest, error)
	CreateDLQRecord(ctx context.Context, arg CreateDLQRecordParams) (ForwardingDlq, error)
	CreateDeliveryJob(ctx context.Context, arg CreateDeliveryJobParams) (DeliveryJob, error)
	CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateMockRule(ctx context.Context, arg CreateMockRuleParams) (MockRule, error)
	CreateOrganization(ctx context.Context, name string) (CreateOrganizationRow, error)
	CreateOutboxJob(ctx context.Context, arg CreateOutboxJobParams) (ForwardingDlq, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateReplayJob(ctx context.Context, arg CreateReplayJobParams) (CreateReplayJobRow, error)
	CreateReplayTestRun(ctx context.Context, arg CreateReplayTestRunParams) (ReplayTestRun, error)
	CreateReplayTestSuite(ctx context.Context, arg CreateReplayTestSuiteParams) (ReplayTestSuite, error)
	CreateSchemaBaseline(ctx context.Context, arg CreateSchemaBaselineParams) (SchemaBaseline, error)
	CreateSchemaDriftEvent(ctx context.Context, arg CreateSchemaDriftEventParams) (SchemaDriftEvent, error)
	CreateSecurityFinding(ctx context.Context, arg CreateSecurityFindingParams) (SecurityFinding, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeactivateAllSchemaBaselines(ctx context.Context, endpointID pgtype.UUID) error
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error
	DeleteAlertChannel(ctx context.Context, id pgtype.UUID) error
	DeleteDLQRecordsByEndpoint(ctx context.Context, endpointID pgtype.UUID) error
	DeleteEndpoint(ctx context.Context, arg DeleteEndpointParams) error
	DeleteEndpointSchema(ctx context.Context, endpointID pgtype.UUID) error
	DeleteEndpointWebhookSecurity(ctx context.Context, endpointID pgtype.UUID) error
	DeleteMockRule(ctx context.Context, arg DeleteMockRuleParams) error
	DeleteProject(ctx context.Context, arg DeleteProjectParams) error
	DeleteReplayTestSuite(ctx context.Context, arg DeleteReplayTestSuiteParams) error
	FailDeliveryJob(ctx context.Context, arg FailDeliveryJobParams) (DeliveryJob, error)
	FailOutboxJob(ctx context.Context, arg FailOutboxJobParams) (ForwardingDlq, error)
	GetAPIKeyByPrefixAndHash(ctx context.Context, arg GetAPIKeyByPrefixAndHashParams) (ApiKey, error)
	GetActiveSchemaBaseline(ctx context.Context, endpointID pgtype.UUID) (SchemaBaseline, error)
	GetAgentScanByIdempotencyKey(ctx context.Context, arg GetAgentScanByIdempotencyKeyParams) (AgentScan, error)
	GetAlertChannelByID(ctx context.Context, id pgtype.UUID) (AlertChannel, error)
	GetCapturedRequestByID(ctx context.Context, id pgtype.UUID) (GetCapturedRequestByIDRow, error)
	GetCapturedRequestByRequestIDStr(ctx context.Context, requestID string) (GetCapturedRequestByRequestIDStrRow, error)
	GetDLQRecordByID(ctx context.Context, id pgtype.UUID) (ForwardingDlq, error)
	GetDeliveryJobByID(ctx context.Context, id pgtype.UUID) (DeliveryJob, error)
	GetDeliveryJobByRequestID(ctx context.Context, requestID pgtype.UUID) (DeliveryJob, error)
	GetEndpointByID(ctx context.Context, arg GetEndpointByIDParams) (Endpoint, error)
	GetEndpointByIDOnly(ctx context.Context, id pgtype.UUID) (Endpoint, error)
	GetEndpointBySlug(ctx context.Context, slug string) (Endpoint, error)
	GetEndpointSchema(ctx context.Context, endpointID pgtype.UUID) (EndpointSchema, error)
	GetEndpointWebhookSecurity(ctx context.Context, endpointID pgtype.UUID) (EndpointWebhookSecurity, error)
	GetEndpointWithOwnership(ctx context.Context, arg GetEndpointWithOwnershipParams) (GetEndpointWithOwnershipRow, error)
	GetFindingStats(ctx context.Context, projectID pgtype.UUID) (GetFindingStatsRow, error)
	GetForwardingConfigByEndpoint(ctx context.Context, endpointID pgtype.UUID) (ForwardingConfig, error)
	GetMatchingMockRule(ctx context.Context, endpointID pgtype.UUID) (MockRule, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetNextSchemaVersion(ctx context.Context, endpointID pgtype.UUID) (int32, error)
	GetOrganizationAISettings(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error)
	GetProjectOrganizationID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetReplayJobByID(ctx context.Context, id pgtype.UUID) (GetReplayJobByIDRow, error)
	GetReplayTestSuiteByID(ctx context.Context, id pgtype.UUID) (ReplayTestSuite, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	ListAPIKeysByProject(ctx context.Context, projectID pgtype.UUID) ([]ListAPIKeysByProjectRow, error)
	ListAgentScansByProject(ctx context.Context, arg ListAgentScansByProjectParams) ([]AgentScan, error)
	ListAlertChannelsByProject(ctx context.Context, projectID pgtype.UUID) ([]AlertChannel, error)
	ListAuditLogsByOrganization(ctx context.Context, arg ListAuditLogsByOrganizationParams) ([]AuditLog, error)
	ListAuditLogsByProject(ctx context.Context, arg ListAuditLogsByProjectParams) ([]AuditLog, error)
	ListAuditLogsByProjectOrOrg(ctx context.Context, arg ListAuditLogsByProjectOrOrgParams) ([]AuditLog, error)
	ListDLQRecordsByEndpoint(ctx context.Context, endpointID pgtype.UUID) ([]ForwardingDlq, error)
	ListDeliveryAttemptsByJobID(ctx context.Context, jobID pgtype.UUID) ([]DeliveryAttempt, error)
	ListDeliveryJobsByEndpoint(ctx context.Context, arg ListDeliveryJobsByEndpointParams) ([]DeliveryJob, error)
	ListEndpointsByProject(ctx context.Context, projectID pgtype.UUID) ([]ListEndpointsByProjectRow, error)
	ListFindingsByProject(ctx context.Context, arg ListFindingsByProjectParams) ([]ListFindingsByProjectRow, error)
	ListMockRulesByEndpoint(ctx context.Context, endpointID pgtype.UUID) ([]MockRule, error)
	ListProjectsByOrg(ctx context.Context, organizationID pgtype.UUID) ([]Project, error)
	ListReplayJobsByProject(ctx context.Context, arg ListReplayJobsByProjectParams) ([]ListReplayJobsByProjectRow, error)
	ListReplayTestRunsBySuite(ctx context.Context, suiteID pgtype.UUID) ([]ReplayTestRun, error)
	ListReplayTestSuitesByProject(ctx context.Context, projectID pgtype.UUID) ([]ReplayTestSuite, error)
	ListRequestsByEndpoint(ctx context.Context, arg ListRequestsByEndpointParams) ([]CapturedRequest, error)
	ListRequestsByProject(ctx context.Context, arg ListRequestsByProjectParams) ([]ListRequestsByProjectRow, error)
	ListSchemaBaselinesByEndpoint(ctx context.Context, endpointID pgtype.UUID) ([]SchemaBaseline, error)
	ListSchemaDriftsByEndpoint(ctx context.Context, endpointID pgtype.UUID) ([]ListSchemaDriftsByEndpointRow, error)
	ListUserMemberships(ctx context.Context, userID pgtype.UUID) ([]ListUserMembershipsRow, error)
	RecordDeliveryAttempt(ctx context.Context, arg RecordDeliveryAttemptParams) (DeliveryAttempt, error)
	RecoverStaleDeliveryJobs(ctx context.Context) error
	RecoverStaleOutboxJobs(ctx context.Context) error
	RequeueDeliveryJob(ctx context.Context, id pgtype.UUID) (DeliveryJob, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (RevokeAPIKeyRow, error)
	ToggleAlertChannel(ctx context.Context, arg ToggleAlertChannelParams) (AlertChannel, error)
	UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateDLQStatus(ctx context.Context, arg UpdateDLQStatusParams) (ForwardingDlq, error)
	UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error)
	UpdateOrganizationAISettings(ctx context.Context, arg UpdateOrganizationAISettingsParams) (Organization, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateReplayJobResult(ctx context.Context, arg UpdateReplayJobResultParams) (UpdateReplayJobResultRow, error)
	UpdateReplayTestRunResult(ctx context.Context, arg UpdateReplayTestRunResultParams) (ReplayTestRun, error)
	UpdateRequestProcessingStatus(ctx context.Context, arg UpdateRequestProcessingStatusParams) error
	UpsertEndpointSchema(ctx context.Context, arg UpsertEndpointSchemaParams) (EndpointSchema, error)
	UpsertEndpointWebhookSecurity(ctx context.Context, arg UpsertEndpointWebhookSecurityParams) (EndpointWebhookSecurity, error)
	UpsertForwardingConfig(ctx context.Context, arg UpsertForwardingConfigParams) (ForwardingConfig, error)
	VerifyAlertChannelOwnership(ctx context.Context, arg VerifyAlertChannelOwnershipParams) (pgtype.UUID, error)
	VerifyDLQRecordOwnership(ctx context.Context, arg VerifyDLQRecordOwnershipParams) (pgtype.UUID, error)
	VerifyDeliveryJobOwnership(ctx context.Context, arg VerifyDeliveryJobOwnershipParams) (pgtype.UUID, error)
	VerifyProjectOwnership(ctx context.Context, arg VerifyProjectOwnershipParams) (pgtype.UUID, error)
	VerifyRequestOwnership(ctx context.Context, arg VerifyRequestOwnershipParams) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
