// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	CreateAlertChannel(ctx context.Context, arg CreateAlertChannelParams) (AlertChannel, error)
	CreateCapturedRequest(ctx context.Context, arg CreateCapturedRequestParams) (CapturedRequest, error)
	CreateDLQRecord(ctx context.Context, arg CreateDLQRecordParams) (ForwardingDlq, error)
	CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateMockRule(ctx context.Context, arg CreateMockRuleParams) (MockRule, error)
	CreateOrganization(ctx context.Context, name string) (Organization, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateReplayJob(ctx context.Context, arg CreateReplayJobParams) (ReplayJob, error)
	CreateSecurityFinding(ctx context.Context, arg CreateSecurityFindingParams) (SecurityFinding, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error
	DeleteAlertChannel(ctx context.Context, id pgtype.UUID) error
	DeleteDLQRecordsByEndpoint(ctx context.Context, endpointID pgtype.UUID) error
	DeleteEndpoint(ctx context.Context, arg DeleteEndpointParams) error
	DeleteEndpointSchema(ctx context.Context, endpointID pgtype.UUID) error
	DeleteEndpointWebhookSecurity(ctx context.Context, endpointID pgtype.UUID) error
	DeleteMockRule(ctx context.Context, arg DeleteMockRuleParams) error
	DeleteProject(ctx context.Context, arg DeleteProjectParams) error
	GetAPIKeyByPrefixAndHash(ctx context.Context, arg GetAPIKeyByPrefixAndHashParams) (ApiKey, error)
	GetAlertChannelByID(ctx context.Context, id pgtype.UUID) (AlertChannel, error)
	GetCapturedRequestByID(ctx context.Context, id pgtype.UUID) (GetCapturedRequestByIDRow, error)
	GetDLQRecordByID(ctx context.Context, id pgtype.UUID) (ForwardingDlq, error)
	GetEndpointByID(ctx context.Context, arg GetEndpointByIDParams) (Endpoint, error)
	GetEndpointByIDOnly(ctx context.Context, id pgtype.UUID) (Endpoint, error)
	GetEndpointBySlug(ctx context.Context, slug string) (Endpoint, error)
	GetEndpointSchema(ctx context.Context, endpointID pgtype.UUID) (EndpointSchema, error)
	GetEndpointWebhookSecurity(ctx context.Context, endpointID pgtype.UUID) (EndpointWebhookSecurity, error)
	GetEndpointWithOwnership(ctx context.Context, arg GetEndpointWithOwnershipParams) (GetEndpointWithOwnershipRow, error)
	GetFindingStats(ctx context.Context, projectID pgtype.UUID) (GetFindingStatsRow, error)
	GetForwardingConfigByEndpoint(ctx context.Context, endpointID pgtype.UUID) (ForwardingConfig, error)
	GetMatchingMockRule(ctx context.Context, endpointID pgtype.UUID) (MockRule, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error)
	GetProjectOrganizationID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	ListAPIKeysByProject(ctx context.Context, projectID pgtype.UUID) ([]ListAPIKeysByProjectRow, error)
	ListAlertChannelsByProject(ctx context.Context, projectID pgtype.UUID) ([]AlertChannel, error)
	ListDLQRecordsByEndpoint(ctx context.Context, endpointID pgtype.UUID) ([]ForwardingDlq, error)
	ListEndpointsByProject(ctx context.Context, projectID pgtype.UUID) ([]ListEndpointsByProjectRow, error)
	ListFindingsByProject(ctx context.Context, arg ListFindingsByProjectParams) ([]ListFindingsByProjectRow, error)
	ListMockRulesByEndpoint(ctx context.Context, endpointID pgtype.UUID) ([]MockRule, error)
	ListProjectsByOrg(ctx context.Context, organizationID pgtype.UUID) ([]Project, error)
	ListReplayJobsByProject(ctx context.Context, arg ListReplayJobsByProjectParams) ([]ListReplayJobsByProjectRow, error)
	ListRequestsByEndpoint(ctx context.Context, arg ListRequestsByEndpointParams) ([]CapturedRequest, error)
	ListRequestsByProject(ctx context.Context, arg ListRequestsByProjectParams) ([]ListRequestsByProjectRow, error)
	ListUserMemberships(ctx context.Context, userID pgtype.UUID) ([]ListUserMembershipsRow, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (RevokeAPIKeyRow, error)
	ToggleAlertChannel(ctx context.Context, arg ToggleAlertChannelParams) (AlertChannel, error)
	UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateDLQStatus(ctx context.Context, arg UpdateDLQStatusParams) (ForwardingDlq, error)
	UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateReplayJobResult(ctx context.Context, arg UpdateReplayJobResultParams) (ReplayJob, error)
	UpdateRequestProcessingStatus(ctx context.Context, arg UpdateRequestProcessingStatusParams) error
	UpsertEndpointSchema(ctx context.Context, arg UpsertEndpointSchemaParams) (EndpointSchema, error)
	UpsertEndpointWebhookSecurity(ctx context.Context, arg UpsertEndpointWebhookSecurityParams) (EndpointWebhookSecurity, error)
	UpsertForwardingConfig(ctx context.Context, arg UpsertForwardingConfigParams) (ForwardingConfig, error)
	VerifyAlertChannelOwnership(ctx context.Context, arg VerifyAlertChannelOwnershipParams) (pgtype.UUID, error)
	VerifyDLQRecordOwnership(ctx context.Context, arg VerifyDLQRecordOwnershipParams) (pgtype.UUID, error)
	VerifyProjectOwnership(ctx context.Context, arg VerifyProjectOwnershipParams) (pgtype.UUID, error)
	VerifyRequestOwnership(ctx context.Context, arg VerifyRequestOwnershipParams) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
