// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replay.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReplayJob = `-- name: CreateReplayJob :one
INSERT INTO replay_jobs (source_request_id, target_type, target_url, status)
VALUES ($1, $2, $3, $4)
RETURNING id, source_request_id, target_type, target_url, status, response_status, response_body, created_at, completed_at
`

type CreateReplayJobParams struct {
	SourceRequestID pgtype.UUID `json:"source_request_id"`
	TargetType      string      `json:"target_type"`
	TargetUrl       pgtype.Text `json:"target_url"`
	Status          string      `json:"status"`
}

func (q *Queries) CreateReplayJob(ctx context.Context, arg CreateReplayJobParams) (ReplayJob, error) {
	row := q.db.QueryRow(ctx, createReplayJob,
		arg.SourceRequestID,
		arg.TargetType,
		arg.TargetUrl,
		arg.Status,
	)
	var i ReplayJob
	err := row.Scan(
		&i.ID,
		&i.SourceRequestID,
		&i.TargetType,
		&i.TargetUrl,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listReplayJobsByProject = `-- name: ListReplayJobsByProject :many
SELECT rj.id, rj.source_request_id, rj.target_type, rj.target_url, rj.status,
       rj.response_status, rj.response_body, rj.created_at, rj.completed_at,
       cr.http_method, cr.request_id, e.name as endpoint_name
FROM replay_jobs rj
JOIN captured_requests cr ON rj.source_request_id = cr.id
JOIN endpoints e ON cr.endpoint_id = e.id
WHERE e.project_id = $1
ORDER BY rj.created_at DESC
LIMIT $2 OFFSET $3
`

type ListReplayJobsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListReplayJobsByProjectRow struct {
	ID              pgtype.UUID        `json:"id"`
	SourceRequestID pgtype.UUID        `json:"source_request_id"`
	TargetType      string             `json:"target_type"`
	TargetUrl       pgtype.Text        `json:"target_url"`
	Status          string             `json:"status"`
	ResponseStatus  pgtype.Int4        `json:"response_status"`
	ResponseBody    pgtype.Text        `json:"response_body"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	HttpMethod      string             `json:"http_method"`
	RequestID       string             `json:"request_id"`
	EndpointName    string             `json:"endpoint_name"`
}

func (q *Queries) ListReplayJobsByProject(ctx context.Context, arg ListReplayJobsByProjectParams) ([]ListReplayJobsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listReplayJobsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReplayJobsByProjectRow
	for rows.Next() {
		var i ListReplayJobsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceRequestID,
			&i.TargetType,
			&i.TargetUrl,
			&i.Status,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.HttpMethod,
			&i.RequestID,
			&i.EndpointName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReplayJobResult = `-- name: UpdateReplayJobResult :one
UPDATE replay_jobs
SET status = $2,
    response_status = $3,
    response_body = $4,
    completed_at = $5
WHERE id = $1
RETURNING id, source_request_id, target_type, target_url, status, response_status, response_body, created_at, completed_at
`

type UpdateReplayJobResultParams struct {
	ID             pgtype.UUID        `json:"id"`
	Status         string             `json:"status"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	ResponseBody   pgtype.Text        `json:"response_body"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateReplayJobResult(ctx context.Context, arg UpdateReplayJobResultParams) (ReplayJob, error) {
	row := q.db.QueryRow(ctx, updateReplayJobResult,
		arg.ID,
		arg.Status,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.CompletedAt,
	)
	var i ReplayJob
	err := row.Scan(
		&i.ID,
		&i.SourceRequestID,
		&i.TargetType,
		&i.TargetUrl,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
