// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCapturedRequest = `-- name: CreateCapturedRequest :one
INSERT INTO captured_requests (
    endpoint_id, request_id, http_method, headers, query_params,
    raw_body, masked_body, parsed_json, client_ip, response_status, processing_status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, endpoint_id, request_id, http_method, headers, query_params, raw_body, masked_body, parsed_json, client_ip, response_status, processing_status, created_at
`

type CreateCapturedRequestParams struct {
	EndpointID       pgtype.UUID `json:"endpoint_id"`
	RequestID        string      `json:"request_id"`
	HttpMethod       string      `json:"http_method"`
	Headers          []byte      `json:"headers"`
	QueryParams      []byte      `json:"query_params"`
	RawBody          pgtype.Text `json:"raw_body"`
	MaskedBody       pgtype.Text `json:"masked_body"`
	ParsedJson       []byte      `json:"parsed_json"`
	ClientIp         *netip.Addr `json:"client_ip"`
	ResponseStatus   pgtype.Int4 `json:"response_status"`
	ProcessingStatus string      `json:"processing_status"`
}

func (q *Queries) CreateCapturedRequest(ctx context.Context, arg CreateCapturedRequestParams) (CapturedRequest, error) {
	row := q.db.QueryRow(ctx, createCapturedRequest,
		arg.EndpointID,
		arg.RequestID,
		arg.HttpMethod,
		arg.Headers,
		arg.QueryParams,
		arg.RawBody,
		arg.MaskedBody,
		arg.ParsedJson,
		arg.ClientIp,
		arg.ResponseStatus,
		arg.ProcessingStatus,
	)
	var i CapturedRequest
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestID,
		&i.HttpMethod,
		&i.Headers,
		&i.QueryParams,
		&i.RawBody,
		&i.MaskedBody,
		&i.ParsedJson,
		&i.ClientIp,
		&i.ResponseStatus,
		&i.ProcessingStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getCapturedRequestByID = `-- name: GetCapturedRequestByID :one
SELECT r.id, r.endpoint_id, r.request_id, r.http_method, r.headers, r.query_params,
       r.raw_body, r.masked_body, r.parsed_json, r.client_ip, r.response_status, r.processing_status, r.created_at,
       e.name as endpoint_name, e.slug as endpoint_slug, e.project_id
FROM captured_requests r
JOIN endpoints e ON r.endpoint_id = e.id
WHERE r.id = $1 LIMIT 1
`

type GetCapturedRequestByIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	EndpointID       pgtype.UUID        `json:"endpoint_id"`
	RequestID        string             `json:"request_id"`
	HttpMethod       string             `json:"http_method"`
	Headers          []byte             `json:"headers"`
	QueryParams      []byte             `json:"query_params"`
	RawBody          pgtype.Text        `json:"raw_body"`
	MaskedBody       pgtype.Text        `json:"masked_body"`
	ParsedJson       []byte             `json:"parsed_json"`
	ClientIp         *netip.Addr        `json:"client_ip"`
	ResponseStatus   pgtype.Int4        `json:"response_status"`
	ProcessingStatus string             `json:"processing_status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	EndpointName     string             `json:"endpoint_name"`
	EndpointSlug     string             `json:"endpoint_slug"`
	ProjectID        pgtype.UUID        `json:"project_id"`
}

func (q *Queries) GetCapturedRequestByID(ctx context.Context, id pgtype.UUID) (GetCapturedRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getCapturedRequestByID, id)
	var i GetCapturedRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.RequestID,
		&i.HttpMethod,
		&i.Headers,
		&i.QueryParams,
		&i.RawBody,
		&i.MaskedBody,
		&i.ParsedJson,
		&i.ClientIp,
		&i.ResponseStatus,
		&i.ProcessingStatus,
		&i.CreatedAt,
		&i.EndpointName,
		&i.EndpointSlug,
		&i.ProjectID,
	)
	return i, err
}

const listRequestsByEndpoint = `-- name: ListRequestsByEndpoint :many
SELECT id, endpoint_id, request_id, http_method, headers, query_params,
       raw_body, masked_body, parsed_json, client_ip, response_status, processing_status, created_at
FROM captured_requests
WHERE endpoint_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRequestsByEndpointParams struct {
	EndpointID pgtype.UUID `json:"endpoint_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListRequestsByEndpoint(ctx context.Context, arg ListRequestsByEndpointParams) ([]CapturedRequest, error) {
	rows, err := q.db.Query(ctx, listRequestsByEndpoint, arg.EndpointID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CapturedRequest
	for rows.Next() {
		var i CapturedRequest
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.RequestID,
			&i.HttpMethod,
			&i.Headers,
			&i.QueryParams,
			&i.RawBody,
			&i.MaskedBody,
			&i.ParsedJson,
			&i.ClientIp,
			&i.ResponseStatus,
			&i.ProcessingStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByProject = `-- name: ListRequestsByProject :many
SELECT r.id, r.endpoint_id, r.request_id, r.http_method, r.headers, r.query_params,
       r.raw_body, r.masked_body, r.parsed_json, r.client_ip, r.response_status, r.processing_status, r.created_at,
       e.name as endpoint_name, e.slug as endpoint_slug
FROM captured_requests r
JOIN endpoints e ON r.endpoint_id = e.id
WHERE e.project_id = $1
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListRequestsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListRequestsByProjectRow struct {
	ID               pgtype.UUID        `json:"id"`
	EndpointID       pgtype.UUID        `json:"endpoint_id"`
	RequestID        string             `json:"request_id"`
	HttpMethod       string             `json:"http_method"`
	Headers          []byte             `json:"headers"`
	QueryParams      []byte             `json:"query_params"`
	RawBody          pgtype.Text        `json:"raw_body"`
	MaskedBody       pgtype.Text        `json:"masked_body"`
	ParsedJson       []byte             `json:"parsed_json"`
	ClientIp         *netip.Addr        `json:"client_ip"`
	ResponseStatus   pgtype.Int4        `json:"response_status"`
	ProcessingStatus string             `json:"processing_status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	EndpointName     string             `json:"endpoint_name"`
	EndpointSlug     string             `json:"endpoint_slug"`
}

func (q *Queries) ListRequestsByProject(ctx context.Context, arg ListRequestsByProjectParams) ([]ListRequestsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listRequestsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestsByProjectRow
	for rows.Next() {
		var i ListRequestsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.RequestID,
			&i.HttpMethod,
			&i.Headers,
			&i.QueryParams,
			&i.RawBody,
			&i.MaskedBody,
			&i.ParsedJson,
			&i.ClientIp,
			&i.ResponseStatus,
			&i.ProcessingStatus,
			&i.CreatedAt,
			&i.EndpointName,
			&i.EndpointSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequestProcessingStatus = `-- name: UpdateRequestProcessingStatus :exec
UPDATE captured_requests
SET processing_status = $2
WHERE id = $1
`

type UpdateRequestProcessingStatusParams struct {
	ID               pgtype.UUID `json:"id"`
	ProcessingStatus string      `json:"processing_status"`
}

func (q *Queries) UpdateRequestProcessingStatus(ctx context.Context, arg UpdateRequestProcessingStatusParams) error {
	_, err := q.db.Exec(ctx, updateRequestProcessingStatus, arg.ID, arg.ProcessingStatus)
	return err
}

const verifyRequestOwnership = `-- name: VerifyRequestOwnership :one
SELECT r.id
FROM captured_requests r
JOIN endpoints e ON e.id = r.endpoint_id
JOIN projects p ON p.id = e.project_id
WHERE r.id = $1 AND p.organization_id = $2
LIMIT 1
`

type VerifyRequestOwnershipParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) VerifyRequestOwnership(ctx context.Context, arg VerifyRequestOwnershipParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyRequestOwnership, arg.ID, arg.OrganizationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
