// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schemas.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateSchemaBaseline = `-- name: ActivateSchemaBaseline :one
UPDATE schema_baselines
SET is_active = TRUE, updated_at = NOW()
WHERE id = $1 AND endpoint_id = $2
RETURNING id, endpoint_id, version, schema_json, source, is_active, created_at, updated_at
`

type ActivateSchemaBaselineParams struct {
	ID         pgtype.UUID `json:"id"`
	EndpointID pgtype.UUID `json:"endpoint_id"`
}

func (q *Queries) ActivateSchemaBaseline(ctx context.Context, arg ActivateSchemaBaselineParams) (SchemaBaseline, error) {
	row := q.db.QueryRow(ctx, activateSchemaBaseline, arg.ID, arg.EndpointID)
	var i SchemaBaseline
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.Version,
		&i.SchemaJson,
		&i.Source,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSchemaBaseline = `-- name: CreateSchemaBaseline :one
INSERT INTO schema_baselines (
    endpoint_id, version, schema_json, source, is_active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, endpoint_id, version, schema_json, source, is_active, created_at, updated_at
`

type CreateSchemaBaselineParams struct {
	EndpointID pgtype.UUID `json:"endpoint_id"`
	Version    int32       `json:"version"`
	SchemaJson []byte      `json:"schema_json"`
	Source     string      `json:"source"`
	IsActive   bool        `json:"is_active"`
}

func (q *Queries) CreateSchemaBaseline(ctx context.Context, arg CreateSchemaBaselineParams) (SchemaBaseline, error) {
	row := q.db.QueryRow(ctx, createSchemaBaseline,
		arg.EndpointID,
		arg.Version,
		arg.SchemaJson,
		arg.Source,
		arg.IsActive,
	)
	var i SchemaBaseline
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.Version,
		&i.SchemaJson,
		&i.Source,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAllSchemaBaselines = `-- name: DeactivateAllSchemaBaselines :exec
UPDATE schema_baselines
SET is_active = FALSE, updated_at = NOW()
WHERE endpoint_id = $1
`

func (q *Queries) DeactivateAllSchemaBaselines(ctx context.Context, endpointID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateAllSchemaBaselines, endpointID)
	return err
}

const getActiveSchemaBaseline = `-- name: GetActiveSchemaBaseline :one
SELECT id, endpoint_id, version, schema_json, source, is_active, created_at, updated_at FROM schema_baselines
WHERE endpoint_id = $1 AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetActiveSchemaBaseline(ctx context.Context, endpointID pgtype.UUID) (SchemaBaseline, error) {
	row := q.db.QueryRow(ctx, getActiveSchemaBaseline, endpointID)
	var i SchemaBaseline
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.Version,
		&i.SchemaJson,
		&i.Source,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextSchemaVersion = `-- name: GetNextSchemaVersion :one
SELECT COALESCE(MAX(version), 0)::int + 1 AS next_version
FROM schema_baselines
WHERE endpoint_id = $1
`

func (q *Queries) GetNextSchemaVersion(ctx context.Context, endpointID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextSchemaVersion, endpointID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const listSchemaBaselinesByEndpoint = `-- name: ListSchemaBaselinesByEndpoint :many
SELECT id, endpoint_id, version, schema_json, source, is_active, created_at, updated_at FROM schema_baselines
WHERE endpoint_id = $1
ORDER BY version DESC
`

func (q *Queries) ListSchemaBaselinesByEndpoint(ctx context.Context, endpointID pgtype.UUID) ([]SchemaBaseline, error) {
	rows, err := q.db.Query(ctx, listSchemaBaselinesByEndpoint, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchemaBaseline
	for rows.Next() {
		var i SchemaBaseline
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.Version,
			&i.SchemaJson,
			&i.Source,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
