// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test_suites.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReplayTestRun = `-- name: CreateReplayTestRun :one
INSERT INTO replay_test_runs (
    suite_id, status, total_steps, passed_steps, failed_steps, total_latency_ms, step_results
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, suite_id, status, total_steps, passed_steps, failed_steps, total_latency_ms, step_results, created_at, completed_at
`

type CreateReplayTestRunParams struct {
	SuiteID        pgtype.UUID `json:"suite_id"`
	Status         string      `json:"status"`
	TotalSteps     int32       `json:"total_steps"`
	PassedSteps    int32       `json:"passed_steps"`
	FailedSteps    int32       `json:"failed_steps"`
	TotalLatencyMs int32       `json:"total_latency_ms"`
	StepResults    []byte      `json:"step_results"`
}

func (q *Queries) CreateReplayTestRun(ctx context.Context, arg CreateReplayTestRunParams) (ReplayTestRun, error) {
	row := q.db.QueryRow(ctx, createReplayTestRun,
		arg.SuiteID,
		arg.Status,
		arg.TotalSteps,
		arg.PassedSteps,
		arg.FailedSteps,
		arg.TotalLatencyMs,
		arg.StepResults,
	)
	var i ReplayTestRun
	err := row.Scan(
		&i.ID,
		&i.SuiteID,
		&i.Status,
		&i.TotalSteps,
		&i.PassedSteps,
		&i.FailedSteps,
		&i.TotalLatencyMs,
		&i.StepResults,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createReplayTestSuite = `-- name: CreateReplayTestSuite :one
INSERT INTO replay_test_suites (
    project_id, name, description, request_ids, target_environment, target_url, renew_idempotency, custom_headers
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, project_id, name, description, request_ids, target_environment, target_url, renew_idempotency, custom_headers, created_at, updated_at
`

type CreateReplayTestSuiteParams struct {
	ProjectID         pgtype.UUID `json:"project_id"`
	Name              string      `json:"name"`
	Description       pgtype.Text `json:"description"`
	RequestIds        []byte      `json:"request_ids"`
	TargetEnvironment string      `json:"target_environment"`
	TargetUrl         pgtype.Text `json:"target_url"`
	RenewIdempotency  bool        `json:"renew_idempotency"`
	CustomHeaders     []byte      `json:"custom_headers"`
}

func (q *Queries) CreateReplayTestSuite(ctx context.Context, arg CreateReplayTestSuiteParams) (ReplayTestSuite, error) {
	row := q.db.QueryRow(ctx, createReplayTestSuite,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.RequestIds,
		arg.TargetEnvironment,
		arg.TargetUrl,
		arg.RenewIdempotency,
		arg.CustomHeaders,
	)
	var i ReplayTestSuite
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.RequestIds,
		&i.TargetEnvironment,
		&i.TargetUrl,
		&i.RenewIdempotency,
		&i.CustomHeaders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReplayTestSuite = `-- name: DeleteReplayTestSuite :exec
DELETE FROM replay_test_suites
WHERE id = $1 AND project_id = $2
`

type DeleteReplayTestSuiteParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) DeleteReplayTestSuite(ctx context.Context, arg DeleteReplayTestSuiteParams) error {
	_, err := q.db.Exec(ctx, deleteReplayTestSuite, arg.ID, arg.ProjectID)
	return err
}

const getReplayTestSuiteByID = `-- name: GetReplayTestSuiteByID :one
SELECT id, project_id, name, description, request_ids, target_environment, target_url, renew_idempotency, custom_headers, created_at, updated_at FROM replay_test_suites
WHERE id = $1
`

func (q *Queries) GetReplayTestSuiteByID(ctx context.Context, id pgtype.UUID) (ReplayTestSuite, error) {
	row := q.db.QueryRow(ctx, getReplayTestSuiteByID, id)
	var i ReplayTestSuite
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.RequestIds,
		&i.TargetEnvironment,
		&i.TargetUrl,
		&i.RenewIdempotency,
		&i.CustomHeaders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReplayTestRunsBySuite = `-- name: ListReplayTestRunsBySuite :many
SELECT id, suite_id, status, total_steps, passed_steps, failed_steps, total_latency_ms, step_results, created_at, completed_at FROM replay_test_runs
WHERE suite_id = $1
ORDER BY created_at DESC
LIMIT 20
`

func (q *Queries) ListReplayTestRunsBySuite(ctx context.Context, suiteID pgtype.UUID) ([]ReplayTestRun, error) {
	rows, err := q.db.Query(ctx, listReplayTestRunsBySuite, suiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReplayTestRun
	for rows.Next() {
		var i ReplayTestRun
		if err := rows.Scan(
			&i.ID,
			&i.SuiteID,
			&i.Status,
			&i.TotalSteps,
			&i.PassedSteps,
			&i.FailedSteps,
			&i.TotalLatencyMs,
			&i.StepResults,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplayTestSuitesByProject = `-- name: ListReplayTestSuitesByProject :many
SELECT id, project_id, name, description, request_ids, target_environment, target_url, renew_idempotency, custom_headers, created_at, updated_at FROM replay_test_suites
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReplayTestSuitesByProject(ctx context.Context, projectID pgtype.UUID) ([]ReplayTestSuite, error) {
	rows, err := q.db.Query(ctx, listReplayTestSuitesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReplayTestSuite
	for rows.Next() {
		var i ReplayTestSuite
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.RequestIds,
			&i.TargetEnvironment,
			&i.TargetUrl,
			&i.RenewIdempotency,
			&i.CustomHeaders,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReplayTestRunResult = `-- name: UpdateReplayTestRunResult :one
UPDATE replay_test_runs
SET status = $2,
    passed_steps = $3,
    failed_steps = $4,
    total_latency_ms = $5,
    step_results = $6,
    completed_at = $7
WHERE id = $1
RETURNING id, suite_id, status, total_steps, passed_steps, failed_steps, total_latency_ms, step_results, created_at, completed_at
`

type UpdateReplayTestRunResultParams struct {
	ID             pgtype.UUID        `json:"id"`
	Status         string             `json:"status"`
	PassedSteps    int32              `json:"passed_steps"`
	FailedSteps    int32              `json:"failed_steps"`
	TotalLatencyMs int32              `json:"total_latency_ms"`
	StepResults    []byte             `json:"step_results"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateReplayTestRunResult(ctx context.Context, arg UpdateReplayTestRunResultParams) (ReplayTestRun, error) {
	row := q.db.QueryRow(ctx, updateReplayTestRunResult,
		arg.ID,
		arg.Status,
		arg.PassedSteps,
		arg.FailedSteps,
		arg.TotalLatencyMs,
		arg.StepResults,
		arg.CompletedAt,
	)
	var i ReplayTestRun
	err := row.Scan(
		&i.ID,
		&i.SuiteID,
		&i.Status,
		&i.TotalSteps,
		&i.PassedSteps,
		&i.FailedSteps,
		&i.TotalLatencyMs,
		&i.StepResults,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const verifyTestSuiteOwnership = `-- name: VerifyTestSuiteOwnership :one
SELECT ts.id
FROM replay_test_suites ts
JOIN projects p ON p.id = ts.project_id
WHERE ts.id = $1 AND p.organization_id = $2
LIMIT 1
`

type VerifyTestSuiteOwnershipParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) VerifyTestSuiteOwnership(ctx context.Context, arg VerifyTestSuiteOwnershipParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyTestSuiteOwnership, arg.ID, arg.OrganizationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
