// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (organization_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, organization_id, user_id, role, created_at
`

type CreateMembershipParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Role           string      `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.OrganizationID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name)
VALUES ($1)
RETURNING id, name, created_at
`

type CreateOrganizationRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOrganization(ctx context.Context, name string) (CreateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, createOrganization, name)
	var i CreateOrganizationRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, organization_id, user_id, role, created_at
FROM memberships
WHERE organization_id = $1 AND user_id = $2 LIMIT 1
`

type GetMembershipParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.OrganizationID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationAISettings = `-- name: GetOrganizationAISettings :one
SELECT id, name, ai_enabled, ai_data_sharing_level, ai_custom_redaction_patterns, created_at
FROM organizations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationAISettings(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationAISettings, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AiEnabled,
		&i.AiDataSharingLevel,
		&i.AiCustomRedactionPatterns,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, ai_enabled, ai_data_sharing_level, ai_custom_redaction_patterns, created_at
FROM organizations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AiEnabled,
		&i.AiDataSharingLevel,
		&i.AiCustomRedactionPatterns,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at
FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, created_at
FROM users
WHERE id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const listUserMemberships = `-- name: ListUserMemberships :many
SELECT m.id, m.organization_id, m.user_id, m.role, m.created_at, o.name as organization_name
FROM memberships m
JOIN organizations o ON m.organization_id = o.id
WHERE m.user_id = $1
ORDER BY m.created_at ASC
`

type ListUserMembershipsRow struct {
	ID               pgtype.UUID        `json:"id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Role             string             `json:"role"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	OrganizationName string             `json:"organization_name"`
}

func (q *Queries) ListUserMemberships(ctx context.Context, userID pgtype.UUID) ([]ListUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listUserMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserMembershipsRow
	for rows.Next() {
		var i ListUserMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganizationAISettings = `-- name: UpdateOrganizationAISettings :one
UPDATE organizations
SET ai_enabled = $2,
    ai_data_sharing_level = $3,
    ai_custom_redaction_patterns = $4
WHERE id = $1
RETURNING id, name, ai_enabled, ai_data_sharing_level, ai_custom_redaction_patterns, created_at
`

type UpdateOrganizationAISettingsParams struct {
	ID                        pgtype.UUID `json:"id"`
	AiEnabled                 bool        `json:"ai_enabled"`
	AiDataSharingLevel        string      `json:"ai_data_sharing_level"`
	AiCustomRedactionPatterns []byte      `json:"ai_custom_redaction_patterns"`
}

func (q *Queries) UpdateOrganizationAISettings(ctx context.Context, arg UpdateOrganizationAISettingsParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationAISettings,
		arg.ID,
		arg.AiEnabled,
		arg.AiDataSharingLevel,
		arg.AiCustomRedactionPatterns,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AiEnabled,
		&i.AiDataSharingLevel,
		&i.AiCustomRedactionPatterns,
		&i.CreatedAt,
	)
	return i, err
}
