// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_security.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEndpointWebhookSecurity = `-- name: DeleteEndpointWebhookSecurity :exec
DELETE FROM endpoint_webhook_security
WHERE endpoint_id = $1
`

func (q *Queries) DeleteEndpointWebhookSecurity(ctx context.Context, endpointID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEndpointWebhookSecurity, endpointID)
	return err
}

const getEndpointWebhookSecurity = `-- name: GetEndpointWebhookSecurity :one
SELECT endpoint_id, provider, encrypted_secret, require_signature, created_at, updated_at
FROM endpoint_webhook_security
WHERE endpoint_id = $1
`

func (q *Queries) GetEndpointWebhookSecurity(ctx context.Context, endpointID pgtype.UUID) (EndpointWebhookSecurity, error) {
	row := q.db.QueryRow(ctx, getEndpointWebhookSecurity, endpointID)
	var i EndpointWebhookSecurity
	err := row.Scan(
		&i.EndpointID,
		&i.Provider,
		&i.EncryptedSecret,
		&i.RequireSignature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEndpointWebhookSecurity = `-- name: UpsertEndpointWebhookSecurity :one
INSERT INTO endpoint_webhook_security (endpoint_id, provider, encrypted_secret, require_signature)
VALUES ($1, $2, $3, $4)
ON CONFLICT (endpoint_id) DO UPDATE SET
    provider = EXCLUDED.provider,
    encrypted_secret = EXCLUDED.encrypted_secret,
    require_signature = EXCLUDED.require_signature,
    updated_at = NOW()
RETURNING endpoint_id, provider, encrypted_secret, require_signature, created_at, updated_at
`

type UpsertEndpointWebhookSecurityParams struct {
	EndpointID       pgtype.UUID `json:"endpoint_id"`
	Provider         string      `json:"provider"`
	EncryptedSecret  string      `json:"encrypted_secret"`
	RequireSignature bool        `json:"require_signature"`
}

func (q *Queries) UpsertEndpointWebhookSecurity(ctx context.Context, arg UpsertEndpointWebhookSecurityParams) (EndpointWebhookSecurity, error) {
	row := q.db.QueryRow(ctx, upsertEndpointWebhookSecurity,
		arg.EndpointID,
		arg.Provider,
		arg.EncryptedSecret,
		arg.RequireSignature,
	)
	var i EndpointWebhookSecurity
	err := row.Scan(
		&i.EndpointID,
		&i.Provider,
		&i.EncryptedSecret,
		&i.RequireSignature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
