// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/security/v1/finding.proto

package securityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_INFO        Severity = 1
	Severity_SEVERITY_LOW         Severity = 2
	Severity_SEVERITY_MEDIUM      Severity = 3
	Severity_SEVERITY_HIGH        Severity = 4
	Severity_SEVERITY_CRITICAL    Severity = 5
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_INFO",
		2: "SEVERITY_LOW",
		3: "SEVERITY_MEDIUM",
		4: "SEVERITY_HIGH",
		5: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_INFO":        1,
		"SEVERITY_LOW":         2,
		"SEVERITY_MEDIUM":      3,
		"SEVERITY_HIGH":        4,
		"SEVERITY_CRITICAL":    5,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_security_v1_finding_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_proto_security_v1_finding_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_proto_security_v1_finding_proto_rawDescGZIP(), []int{0}
}

type PolicyAction int32

const (
	PolicyAction_POLICY_ACTION_UNSPECIFIED PolicyAction = 0
	PolicyAction_POLICY_ACTION_ALLOW       PolicyAction = 1
	PolicyAction_POLICY_ACTION_WARN        PolicyAction = 2
	PolicyAction_POLICY_ACTION_ALERT       PolicyAction = 3
	PolicyAction_POLICY_ACTION_MASK        PolicyAction = 4
	PolicyAction_POLICY_ACTION_BLOCK       PolicyAction = 5
)

// Enum value maps for PolicyAction.
var (
	PolicyAction_name = map[int32]string{
		0: "POLICY_ACTION_UNSPECIFIED",
		1: "POLICY_ACTION_ALLOW",
		2: "POLICY_ACTION_WARN",
		3: "POLICY_ACTION_ALERT",
		4: "POLICY_ACTION_MASK",
		5: "POLICY_ACTION_BLOCK",
	}
	PolicyAction_value = map[string]int32{
		"POLICY_ACTION_UNSPECIFIED": 0,
		"POLICY_ACTION_ALLOW":       1,
		"POLICY_ACTION_WARN":        2,
		"POLICY_ACTION_ALERT":       3,
		"POLICY_ACTION_MASK":        4,
		"POLICY_ACTION_BLOCK":       5,
	}
)

func (x PolicyAction) Enum() *PolicyAction {
	p := new(PolicyAction)
	*p = x
	return p
}

func (x PolicyAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_security_v1_finding_proto_enumTypes[1].Descriptor()
}

func (PolicyAction) Type() protoreflect.EnumType {
	return &file_proto_security_v1_finding_proto_enumTypes[1]
}

func (x PolicyAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyAction.Descriptor instead.
func (PolicyAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_security_v1_finding_proto_rawDescGZIP(), []int{1}
}

type SecurityFinding struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestId      string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RuleId         string                 `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Category       string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Type           string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Severity       Severity               `protobuf:"varint,6,opt,name=severity,proto3,enum=apisentinel.security.v1.Severity" json:"severity,omitempty"`
	Action         PolicyAction           `protobuf:"varint,7,opt,name=action,proto3,enum=apisentinel.security.v1.PolicyAction" json:"action,omitempty"`
	FieldPath      string                 `protobuf:"bytes,8,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Message        string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	EvidenceMasked string                 `protobuf:"bytes,10,opt,name=evidence_masked,json=evidenceMasked,proto3" json:"evidence_masked,omitempty"`
	Confidence     float64                `protobuf:"fixed64,11,opt,name=confidence,proto3" json:"confidence,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FilePath       string                 `protobuf:"bytes,13,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	LineNumber     int32                  `protobuf:"varint,14,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SecurityFinding) Reset() {
	*x = SecurityFinding{}
	mi := &file_proto_security_v1_finding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityFinding) ProtoMessage() {}

func (x *SecurityFinding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_security_v1_finding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityFinding.ProtoReflect.Descriptor instead.
func (*SecurityFinding) Descriptor() ([]byte, []int) {
	return file_proto_security_v1_finding_proto_rawDescGZIP(), []int{0}
}

func (x *SecurityFinding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecurityFinding) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SecurityFinding) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *SecurityFinding) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SecurityFinding) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SecurityFinding) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *SecurityFinding) GetAction() PolicyAction {
	if x != nil {
		return x.Action
	}
	return PolicyAction_POLICY_ACTION_UNSPECIFIED
}

func (x *SecurityFinding) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *SecurityFinding) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SecurityFinding) GetEvidenceMasked() string {
	if x != nil {
		return x.EvidenceMasked
	}
	return ""
}

func (x *SecurityFinding) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SecurityFinding) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SecurityFinding) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *SecurityFinding) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

var File_proto_security_v1_finding_proto protoreflect.FileDescriptor

const file_proto_security_v1_finding_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/security/v1/finding.proto\x12\x17apisentinel.security.v1\"\xe6\x03\n" +
	"\x0fSecurityFinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x17\n" +
	"\arule_id\x18\x03 \x01(\tR\x06ruleId\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12=\n" +
	"\bseverity\x18\x06 \x01(\x0e2!.apisentinel.security.v1.SeverityR\bseverity\x12=\n" +
	"\x06action\x18\a \x01(\x0e2%.apisentinel.security.v1.PolicyActionR\x06action\x12\x1d\n" +
	"\n" +
	"field_path\x18\b \x01(\tR\tfieldPath\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\x12'\n" +
	"\x0fevidence_masked\x18\n" +
	" \x01(\tR\x0eevidenceMasked\x12\x1e\n" +
	"\n" +
	"confidence\x18\v \x01(\x01R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tfile_path\x18\r \x01(\tR\bfilePath\x12\x1f\n" +
	"\vline_number\x18\x0e \x01(\x05R\n" +
	"lineNumber*\x88\x01\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x02\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x03\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x04\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x05*\xa8\x01\n" +
	"\fPolicyAction\x12\x1d\n" +
	"\x19POLICY_ACTION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13POLICY_ACTION_ALLOW\x10\x01\x12\x16\n" +
	"\x12POLICY_ACTION_WARN\x10\x02\x12\x17\n" +
	"\x13POLICY_ACTION_ALERT\x10\x03\x12\x16\n" +
	"\x12POLICY_ACTION_MASK\x10\x04\x12\x17\n" +
	"\x13POLICY_ACTION_BLOCK\x10\x05BNZLgithub.com/apisentinel/apisentinel/pkg/genproto/proto/security/v1;securityv1b\x06proto3"

var (
	file_proto_security_v1_finding_proto_rawDescOnce sync.Once
	file_proto_security_v1_finding_proto_rawDescData []byte
)

func file_proto_security_v1_finding_proto_rawDescGZIP() []byte {
	file_proto_security_v1_finding_proto_rawDescOnce.Do(func() {
		file_proto_security_v1_finding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_security_v1_finding_proto_rawDesc), len(file_proto_security_v1_finding_proto_rawDesc)))
	})
	return file_proto_security_v1_finding_proto_rawDescData
}

var file_proto_security_v1_finding_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_security_v1_finding_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_security_v1_finding_proto_goTypes = []any{
	(Severity)(0),           // 0: apisentinel.security.v1.Severity
	(PolicyAction)(0),       // 1: apisentinel.security.v1.PolicyAction
	(*SecurityFinding)(nil), // 2: apisentinel.security.v1.SecurityFinding
}
var file_proto_security_v1_finding_proto_depIdxs = []int32{
	0, // 0: apisentinel.security.v1.SecurityFinding.severity:type_name -> apisentinel.security.v1.Severity
	1, // 1: apisentinel.security.v1.SecurityFinding.action:type_name -> apisentinel.security.v1.PolicyAction
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_security_v1_finding_proto_init() }
func file_proto_security_v1_finding_proto_init() {
	if File_proto_security_v1_finding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_security_v1_finding_proto_rawDesc), len(file_proto_security_v1_finding_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_security_v1_finding_proto_goTypes,
		DependencyIndexes: file_proto_security_v1_finding_proto_depIdxs,
		EnumInfos:         file_proto_security_v1_finding_proto_enumTypes,
		MessageInfos:      file_proto_security_v1_finding_proto_msgTypes,
	}.Build()
	File_proto_security_v1_finding_proto = out.File
	file_proto_security_v1_finding_proto_goTypes = nil
	file_proto_security_v1_finding_proto_depIdxs = nil
}
