// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/agent/v1/agent.proto

package agentv1

import (
	v1 "github.com/apisentinel/apisentinel/pkg/genproto/proto/replay/v1"
	v11 "github.com/apisentinel/apisentinel/pkg/genproto/proto/security/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_ScanEvent
	//	*AgentMessage_ReplayResult
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *AgentHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetScanEvent() *AgentScanEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ScanEvent); ok {
			return x.ScanEvent
		}
	}
	return nil
}

func (x *AgentMessage) GetReplayResult() *v1.ReplayResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ReplayResult); ok {
			return x.ReplayResult
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *AgentHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_ScanEvent struct {
	ScanEvent *AgentScanEvent `protobuf:"bytes,3,opt,name=scan_event,json=scanEvent,proto3,oneof"`
}

type AgentMessage_ReplayResult struct {
	ReplayResult *v1.ReplayResponse `protobuf:"bytes,4,opt,name=replay_result,json=replayResult,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_ScanEvent) isAgentMessage_Payload() {}

func (*AgentMessage_ReplayResult) isAgentMessage_Payload() {}

type CloudMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CloudMessage_HeartbeatAck
	//	*CloudMessage_ReplayCommand
	//	*CloudMessage_ConfigUpdate
	Payload       isCloudMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudMessage) Reset() {
	*x = CloudMessage{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudMessage) ProtoMessage() {}

func (x *CloudMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudMessage.ProtoReflect.Descriptor instead.
func (*CloudMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CloudMessage) GetPayload() isCloudMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CloudMessage) GetHeartbeatAck() *CloudHeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*CloudMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *CloudMessage) GetReplayCommand() *v1.ReplayRequest {
	if x != nil {
		if x, ok := x.Payload.(*CloudMessage_ReplayCommand); ok {
			return x.ReplayCommand
		}
	}
	return nil
}

func (x *CloudMessage) GetConfigUpdate() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Payload.(*CloudMessage_ConfigUpdate); ok {
			return x.ConfigUpdate
		}
	}
	return nil
}

type isCloudMessage_Payload interface {
	isCloudMessage_Payload()
}

type CloudMessage_HeartbeatAck struct {
	HeartbeatAck *CloudHeartbeatAck `protobuf:"bytes,1,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type CloudMessage_ReplayCommand struct {
	ReplayCommand *v1.ReplayRequest `protobuf:"bytes,2,opt,name=replay_command,json=replayCommand,proto3,oneof"`
}

type CloudMessage_ConfigUpdate struct {
	ConfigUpdate *ConfigUpdate `protobuf:"bytes,3,opt,name=config_update,json=configUpdate,proto3,oneof"`
}

func (*CloudMessage_HeartbeatAck) isCloudMessage_Payload() {}

func (*CloudMessage_ReplayCommand) isCloudMessage_Payload() {}

func (*CloudMessage_ConfigUpdate) isCloudMessage_Payload() {}

type AgentHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHeartbeat) Reset() {
	*x = AgentHeartbeat{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeat) ProtoMessage() {}

func (x *AgentHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeat.ProtoReflect.Descriptor instead.
func (*AgentHeartbeat) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentHeartbeat) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentHeartbeat) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentHeartbeat) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentHeartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CloudHeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudHeartbeatAck) Reset() {
	*x = CloudHeartbeatAck{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudHeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudHeartbeatAck) ProtoMessage() {}

func (x *CloudHeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudHeartbeatAck.ProtoReflect.Descriptor instead.
func (*CloudHeartbeatAck) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CloudHeartbeatAck) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AgentScanEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ScanType      string                 `protobuf:"bytes,2,opt,name=scan_type,json=scanType,proto3" json:"scan_type,omitempty"` // "PRE_PUSH", "PRE_COMMIT", "CLI"
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Findings      []*v11.SecurityFinding `protobuf:"bytes,4,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentScanEvent) Reset() {
	*x = AgentScanEvent{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentScanEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentScanEvent) ProtoMessage() {}

func (x *AgentScanEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentScanEvent.ProtoReflect.Descriptor instead.
func (*AgentScanEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentScanEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AgentScanEvent) GetScanType() string {
	if x != nil {
		return x.ScanType
	}
	return ""
}

func (x *AgentScanEvent) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *AgentScanEvent) GetFindings() []*v11.SecurityFinding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type ConfigUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SecretPatterns []string               `protobuf:"bytes,1,rep,name=secret_patterns,json=secretPatterns,proto3" json:"secret_patterns,omitempty"`
	BlockOnSecret  bool                   `protobuf:"varint,2,opt,name=block_on_secret,json=blockOnSecret,proto3" json:"block_on_secret,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigUpdate) GetSecretPatterns() []string {
	if x != nil {
		return x.SecretPatterns
	}
	return nil
}

func (x *ConfigUpdate) GetBlockOnSecret() bool {
	if x != nil {
		return x.BlockOnSecret
	}
	return false
}

type SyncScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Repository    string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	CommitHash    string                 `protobuf:"bytes,4,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	Findings      []*v11.SecurityFinding `protobuf:"bytes,5,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncScanRequest) Reset() {
	*x = SyncScanRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncScanRequest) ProtoMessage() {}

func (x *SyncScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncScanRequest.ProtoReflect.Descriptor instead.
func (*SyncScanRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SyncScanRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SyncScanRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *SyncScanRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *SyncScanRequest) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *SyncScanRequest) GetFindings() []*v11.SecurityFinding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type SyncScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // "ALLOW", "BLOCK", "WARN"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncScanResponse) Reset() {
	*x = SyncScanResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncScanResponse) ProtoMessage() {}

func (x *SyncScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncScanResponse.ProtoReflect.Descriptor instead.
func (*SyncScanResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SyncScanResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SyncScanResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SyncScanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_agent_v1_agent_proto protoreflect.FileDescriptor

const file_proto_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/agent/v1/agent.proto\x12\x14apisentinel.agent.v1\x1a\x1fproto/security/v1/finding.proto\x1a\x1cproto/replay/v1/replay.proto\"\x8f\x02\n" +
	"\fAgentMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12D\n" +
	"\theartbeat\x18\x02 \x01(\v2$.apisentinel.agent.v1.AgentHeartbeatH\x00R\theartbeat\x12E\n" +
	"\n" +
	"scan_event\x18\x03 \x01(\v2$.apisentinel.agent.v1.AgentScanEventH\x00R\tscanEvent\x12L\n" +
	"\rreplay_result\x18\x04 \x01(\v2%.apisentinel.replay.v1.ReplayResponseH\x00R\freplayResultB\t\n" +
	"\apayload\"\x83\x02\n" +
	"\fCloudMessage\x12N\n" +
	"\rheartbeat_ack\x18\x01 \x01(\v2'.apisentinel.agent.v1.CloudHeartbeatAckH\x00R\fheartbeatAck\x12M\n" +
	"\x0ereplay_command\x18\x02 \x01(\v2$.apisentinel.replay.v1.ReplayRequestH\x00R\rreplayCommand\x12I\n" +
	"\rconfig_update\x18\x03 \x01(\v2\".apisentinel.agent.v1.ConfigUpdateH\x00R\fconfigUpdateB\t\n" +
	"\apayload\"t\n" +
	"\x0eAgentHeartbeat\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"1\n" +
	"\x11CloudHeartbeatAck\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xae\x01\n" +
	"\x0eAgentScanEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\tscan_type\x18\x02 \x01(\tR\bscanType\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12D\n" +
	"\bfindings\x18\x04 \x03(\v2(.apisentinel.security.v1.SecurityFindingR\bfindings\"_\n" +
	"\fConfigUpdate\x12'\n" +
	"\x0fsecret_patterns\x18\x01 \x03(\tR\x0esecretPatterns\x12&\n" +
	"\x0fblock_on_secret\x18\x02 \x01(\bR\rblockOnSecret\"\xcb\x01\n" +
	"\x0fSyncScanRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12\x1f\n" +
	"\vcommit_hash\x18\x04 \x01(\tR\n" +
	"commitHash\x12D\n" +
	"\bfindings\x18\x05 \x03(\v2(.apisentinel.security.v1.SecurityFindingR\bfindings\"`\n" +
	"\x10SyncScanResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xce\x01\n" +
	"\fAgentService\x12\\\n" +
	"\x0eConnectSession\x12\".apisentinel.agent.v1.AgentMessage\x1a\".apisentinel.agent.v1.CloudMessage(\x010\x01\x12`\n" +
	"\x0fSyncScanResults\x12%.apisentinel.agent.v1.SyncScanRequest\x1a&.apisentinel.agent.v1.SyncScanResponseBHZFgithub.com/apisentinel/apisentinel/pkg/genproto/proto/agent/v1;agentv1b\x06proto3"

var (
	file_proto_agent_v1_agent_proto_rawDescOnce sync.Once
	file_proto_agent_v1_agent_proto_rawDescData []byte
)

func file_proto_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)))
	})
	return file_proto_agent_v1_agent_proto_rawDescData
}

var file_proto_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_agent_v1_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),        // 0: apisentinel.agent.v1.AgentMessage
	(*CloudMessage)(nil),        // 1: apisentinel.agent.v1.CloudMessage
	(*AgentHeartbeat)(nil),      // 2: apisentinel.agent.v1.AgentHeartbeat
	(*CloudHeartbeatAck)(nil),   // 3: apisentinel.agent.v1.CloudHeartbeatAck
	(*AgentScanEvent)(nil),      // 4: apisentinel.agent.v1.AgentScanEvent
	(*ConfigUpdate)(nil),        // 5: apisentinel.agent.v1.ConfigUpdate
	(*SyncScanRequest)(nil),     // 6: apisentinel.agent.v1.SyncScanRequest
	(*SyncScanResponse)(nil),    // 7: apisentinel.agent.v1.SyncScanResponse
	(*v1.ReplayResponse)(nil),   // 8: apisentinel.replay.v1.ReplayResponse
	(*v1.ReplayRequest)(nil),    // 9: apisentinel.replay.v1.ReplayRequest
	(*v11.SecurityFinding)(nil), // 10: apisentinel.security.v1.SecurityFinding
}
var file_proto_agent_v1_agent_proto_depIdxs = []int32{
	2,  // 0: apisentinel.agent.v1.AgentMessage.heartbeat:type_name -> apisentinel.agent.v1.AgentHeartbeat
	4,  // 1: apisentinel.agent.v1.AgentMessage.scan_event:type_name -> apisentinel.agent.v1.AgentScanEvent
	8,  // 2: apisentinel.agent.v1.AgentMessage.replay_result:type_name -> apisentinel.replay.v1.ReplayResponse
	3,  // 3: apisentinel.agent.v1.CloudMessage.heartbeat_ack:type_name -> apisentinel.agent.v1.CloudHeartbeatAck
	9,  // 4: apisentinel.agent.v1.CloudMessage.replay_command:type_name -> apisentinel.replay.v1.ReplayRequest
	5,  // 5: apisentinel.agent.v1.CloudMessage.config_update:type_name -> apisentinel.agent.v1.ConfigUpdate
	10, // 6: apisentinel.agent.v1.AgentScanEvent.findings:type_name -> apisentinel.security.v1.SecurityFinding
	10, // 7: apisentinel.agent.v1.SyncScanRequest.findings:type_name -> apisentinel.security.v1.SecurityFinding
	0,  // 8: apisentinel.agent.v1.AgentService.ConnectSession:input_type -> apisentinel.agent.v1.AgentMessage
	6,  // 9: apisentinel.agent.v1.AgentService.SyncScanResults:input_type -> apisentinel.agent.v1.SyncScanRequest
	1,  // 10: apisentinel.agent.v1.AgentService.ConnectSession:output_type -> apisentinel.agent.v1.CloudMessage
	7,  // 11: apisentinel.agent.v1.AgentService.SyncScanResults:output_type -> apisentinel.agent.v1.SyncScanResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_agent_v1_agent_proto_init() }
func file_proto_agent_v1_agent_proto_init() {
	if File_proto_agent_v1_agent_proto != nil {
		return
	}
	file_proto_agent_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_ScanEvent)(nil),
		(*AgentMessage_ReplayResult)(nil),
	}
	file_proto_agent_v1_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*CloudMessage_HeartbeatAck)(nil),
		(*CloudMessage_ReplayCommand)(nil),
		(*CloudMessage_ConfigUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_v1_agent_proto = out.File
	file_proto_agent_v1_agent_proto_goTypes = nil
	file_proto_agent_v1_agent_proto_depIdxs = nil
}
